### ISSUE TITLE
Error text at start of completion files

### ISSUE THREAD

**Issue by madhogs** [Foxboron/sbctl#107]
All of the completion files have the text `‼ Failed to find ESP: failed to find EFI system partition` at the start, which in fish shell at least is causing errors each time sbctl is used in a new terminal window.

```
❯ head /usr/share/fish/vendor_completions.d/sbctl.fish
‼ Failed to find ESP: failed to find EFI system partition
# fish completion for sbctl                                -*- shell-script -*-

function __sbctl_debug
    set file "$BASH_COMP_DEBUG_FILE"
    if test -n "$file"
        echo "$argv" >> $file
    end
end
```

```
❯ head /usr/share/bash-completion/completions/sbctl
‼ Failed to find ESP: failed to find EFI system partition
# bash completion for sbctl                                -*- shell-script -*-

__sbctl_debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}
```

```
❯ head /usr/share/zsh/site-functions/_sbctl
‼ Failed to find ESP: failed to find EFI system partition
#compdef _sbctl sbctl

# zsh completion for sbctl                                -*- shell-script -*-

__sbctl_debug()
{
    local file="$BASH_COMP_DEBUG_FILE"
    if [[ -n ${file} ]]; then
        echo "$*" >> "${file}"
```

This is on Arch Linux with the sbctl package from the Community repository, which otherwise is working well on my system.

**Comment by Foxboron** [comment]
Ouch! Thanks for the report :D

**Comment by ericonr** [comment]
I think outputting to stderr should be enough?

**Comment by Foxboron** [comment]
@ericonr I'm contemplating if it make sense to have it error out during help at all. It fails when we enroll the bundle flags and I think just having empty string is fine. It will error out when you try make a bundle anyway.

**Comment by eNV25** [comment]
I think error messages should go stderr, preferably.

But in this case this code should not be running at all.
