### ISSUE TITLE
OS has been blocked by the current security policy

### ISSUE THREAD

**Issue by jTnqr** [Foxboron/sbctl#109]
I successfully ran `create-keys` and `enroll-keys`, but when I restart and enable secure boot. My PC can't boot any OS, it says 'OS(Manjaro or Windows Boot Manager) has been blocked by the current security policy'. Am I missing something? Right now I can't boot to Linux but I can boot to Windows 11 after restoring factory PK. 

The step that I did:
1. Bios Settings -> Secure Boot off
2. Bios Settings -> Clear PK
3. Save and restart to Linux
4. `sbctl status`
5. `sbctl create-keys`
6. `sbctl enroll-keys`
7. Restart
8. Bios Settings -> Secure Boot on
9. Save and restart

OS: Manjaro 21.1.3 - Linux 5.15 & Windows 11 Insider Build 22509
Laptop: Lenovo Legion 5 15ACH6H

**Comment by Foxboron** [comment]
Which files did you sign with `sbctl` after enrolling keys?

**Comment by jTnqr** [comment]
Umm what files?

**Comment by jTnqr** [comment]
Is the one after 'Key creation and enrollment'? okay, my bad.

**Comment by jTnqr** [comment]
I suggest that you should improve the usage section. Thanks :)

**Comment by jTnqr** [comment]
I didn't sign any files since I can't boot into Linux

**Comment by jTnqr** [comment]
Now I can boot to Linux but when I'm making a stub it says "/etc/kernel/cmdline doesn't exist."

**Comment by jTnqr** [comment]
OK I just fixed it using `ln -s /proc/cmdline /etc/kernel/cmdline`
