### ISSUE TITLE
open /usr/share/secureboot/GUID: no such file or directory

### ISSUE THREAD

**Issue by talhabalaj** [Foxboron/sbctl#110]
I had this tool installed for a while now but I used it today and got the following error.

![image](https://user-images.githubusercontent.com/17191475/145682816-0abd446a-509f-4385-8cf7-23775f53bd5d.png)

**Comment by ericonr** [comment]
I think you need `sbctl create-keys` to fix that, but I guess it would be nice to have `status` working prior to that.

**Comment by talhabalaj** [comment]
It worked, thanks. I used this tool before. `status` used to work without creating keys.
