### ISSUE TITLE
[Idea] support importing the microsoft keys

### ISSUE THREAD

**Issue by yaktoma2007** [Foxboron/sbctl#112]
if the microsoft keys could be imported, linux efi binaries can be signed with the microsoft keys and have secureboot+dual-boot support. with windows 11. you could sign windows 11 efi binaries with your own keys, but after updates you sometimes need to resign those binaries and that is really annoying.

**Comment by Foxboron** [comment]
Yo,

The new release of `sbctl` supports enrolling microsoft keys. Isn't this what you want?

https://github.com/Foxboron/sbctl/releases/tag/0.8
