### ISSUE TITLE
Error when trying to enroll keys

### ISSUE THREAD

**Issue by ShabirK21** [Foxboron/sbctl#115]
I get the error
"File is immutable: /sys/firmware/efi/efivars/...."
"File is immutable: /sys/firmware/efi/efivars/...."
"File is immutable: /sys/firmware/efi/efivars/...."
You need to chattr -i files in efivarfs

**Comment by Foxboron** [comment]
Please use `chattr -i` on the listed files.

**Comment by ShabirK21** [comment]
I tried that and tried enrolling but get the error "could not find any TPM Eventlog in the system" eventhough sbctl status shows vendors:Microsoft

**Comment by Foxboron** [comment]
Did you ever actually `enroll-keys`? Did you reset the Secure Boot keys before trying to enroll your own keys?

**Comment by ShabirK21** [comment]
yes i have tried it with cryptboot but it didn't work. I did reset it after

**Comment by Foxboron** [comment]
Right, please post the full output of `sudo sbctl status` and include the output of `sudo hexdump -C /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c`

**Comment by ShabirK21** [comment]
I'm quite new to this, thanks for the help

sbctl status output :
Installed:      ✓ sbctl is installed
Owner GUID:     41257d6b-44a8-4cc9-a8c0-4057e6cb58c3
Setup Mode:     ✓ Disabled
Secure Boot:    ✗ Disabled
Vendor Keys:    microsoft

sudo hexdump -C /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c output ;

00000000  27 00 00 00 a1 59 c0 a5  e4 94 a7 4a 87 b5 ab 15  |'....Y.....J....|
00000010  5c 2b f0 72 54 03 00 00  00 00 00 00 38 03 00 00  |\+.rT.......8...|
00000020  94 d7 4f e0 3e 03 a0 46  81 d2 04 8e 8d a1 43 2e  |..O.>..F......C.|
00000030  30 82 03 24 30 82 02 0c  a0 03 02 01 02 02 10 99  |0..$0...........|
00000040  4f 8b 12 db 0c 8d b2 49  6e d7 0f fb 2d d9 13 30  |O......In...-..0|
00000050  0d 06 09 2a 86 48 86 f7  0d 01 01 0b 05 00 30 25  |...*.H........0%|
00000060  31 23 30 21 06 03 55 04  03 13 1a 54 72 75 73 74  |1#0!..U....Trust|
00000070  20 2d 20 4c 65 6e 6f 76  6f 20 43 65 72 74 69 66  | - Lenovo Certif|
00000080  69 63 61 74 65 30 1e 17  0d 31 32 30 36 32 30 30  |icate0...1206200|
00000090  32 31 36 34 37 5a 17 0d  33 39 31 32 33 31 32 33  |21647Z..39123123|
000000a0  35 39 35 39 5a 30 1b 31  19 30 17 06 03 55 04 03  |5959Z0.1.0...U..|
000000b0  13 10 49 64 65 61 70 61  64 20 50 72 6f 64 75 63  |..Ideapad Produc|
000000c0  74 73 30 82 01 22 30 0d  06 09 2a 86 48 86 f7 0d  |ts0.."0...*.H...|
000000d0  01 01 01 05 00 03 82 01  0f 00 30 82 01 0a 02 82  |..........0.....|
000000e0  01 01 00 e1 ec 19 1d f8  2e 40 a9 10 0b 22 6f 1c  |.........@..."o.|
000000f0  5b 99 8c 82 16 6b 52 69  f1 02 22 f7 dd 7b 32 e3  |[....kRi.."..{2.|
00000100  17 79 32 6d 08 d9 ee d2  f1 18 5b aa 62 80 6d 65  |.y2m......[.b.me|
00000110  59 a5 92 36 0d 2a 52 78  7d f6 1b 4a 2e 21 2e 13  |Y..6.*Rx}..J.!..|
00000120  6a f6 0d 24 dc 8b d9 92  e1 b2 3b 3c 66 1f 16 37  |j..$......;<f..7|
00000130  9f d6 9d c6 9e 1c 55 14  99 12 4b 1e 7f 61 d3 0a  |......U...K..a..|
00000140  5b d4 3f e5 ed 89 e3 7a  42 58 5b e5 94 6d 77 6a  |[.?....zBX[..mwj|
00000150  4c 6e 40 5d d9 76 1f fc  e6 54 55 88 03 ec f9 a6  |Ln@].v...TU.....|
00000160  73 eb 6b 5c 0e a3 56 a3  41 f8 4d c3 a0 48 85 c9  |s.k\..V.A.M..H..|
00000170  2d ed 5a d1 bc a7 e4 09  64 cd 60 b6 f4 bd 5a 18  |-.Z.....d.`...Z.|
00000180  09 d1 12 f6 da d1 8d ae  c9 a2 b6 df af 57 f4 74  |.............W.t|
00000190  bb fa 6b 50 9a 6c 62 11  84 92 38 fe 76 b6 3d b9  |..kP.lb...8.v.=.|
000001a0  58 15 67 6d 7d c9 c9 39  60 73 f6 0f 0f 53 9c e0  |X.gm}..9`s...S..|
000001b0  c7 74 1f 27 6e cc 69 2d  aa f1 c4 ff 35 14 57 df  |.t.'n.i-....5.W.|
000001c0  05 0a 4f 7e 38 25 7c cb  f5 c0 58 e4 8f 27 69 6c  |..O~8%|...X..'il|
000001d0  ac 4a 8b d4 c9 83 df f3  39 0e e2 be 80 d5 b6 1d  |.J......9.......|
000001e0  3c a9 a9 02 03 01 00 01  a3 5a 30 58 30 56 06 03  |<........Z0X0V..|
000001f0  55 1d 01 04 4f 30 4d 80  10 62 ee 60 7e 86 80 18  |U...O0M..b.`~...|
00000200  90 88 30 aa ab d4 2d b9  22 a1 27 30 25 31 23 30  |..0...-.".'0%1#0|
00000210  21 06 03 55 04 03 13 1a  54 72 75 73 74 20 2d 20  |!..U....Trust - |
00000220  4c 65 6e 6f 76 6f 20 43  65 72 74 69 66 69 63 61  |Lenovo Certifica|
00000230  74 65 82 10 5e d2 e5 ff  6b f8 fd 9e 40 09 60 46  |te..^...k...@.`F|
00000240  0a a2 c0 07 30 0d 06 09  2a 86 48 86 f7 0d 01 01  |....0...*.H.....|
00000250  0b 05 00 03 82 01 01 00  88 1d 46 75 74 67 2a 99  |..........Futg*.|
00000260  7a f7 d1 91 5f 9e 5d f1  5c 82 72 64 6f f3 71 44  |z..._.].\.rdo.qD|
00000270  f1 43 6d f9 8c 63 74 ac  1c f8 f5 fc f9 42 a9 cf  |.Cm..ct......B..|
00000280  1b 57 01 6a 4c 4d c0 67  57 fc 69 b3 2d b5 b6 a8  |.W.jLM.gW.i.-...|
00000290  c0 6e 0c 13 e2 17 02 d9  99 a9 a1 bb 0c 12 cc 68  |.n.............h|
000002a0  22 ab 78 7c d6 89 41 4c  b5 8f 53 0e 5d 9a a5 bb  |".x|..AL..S.]...|
000002b0  e4 da 76 38 33 9a f3 72  d0 de f9 52 1a 69 67 b8  |..v83..r...R.ig.|
000002c0  55 b9 4a ff f1 a4 d3 32  29 98 95 cb 6c 42 82 7f  |U.J....2)...lB..|
000002d0  b6 83 35 c1 e5 aa ea 70  38 03 b5 76 2f 4a b5 19  |..5....p8..v/J..|
000002e0  77 25 64 7d d2 21 72 47  d7 0c 50 32 c8 cc 4c 21  |w%d}.!rG..P2..L!|
000002f0  d2 b6 3b 61 5a 4d f4 92  b6 1f 5d c2 1e b9 79 4c  |..;aZM....]...yL|
00000300  fb 25 f7 db 66 b8 e4 2c  3a 2b 14 fe 9f f4 92 a8  |.%..f..,:+......|
00000310  d3 51 f5 96 49 56 eb 7b  cb cf d6 ab 2f 36 72 43  |.Q..IV.{..../6rC|
00000320  11 2c f0 75 87 35 ce e1  3a 13 d0 87 d6 bb 50 61  |.,.u.5..:.....Pa|
00000330  dc 2e 9d 24 4f 10 ed fe  93 c5 bd 78 ca 50 5f 13  |...$O......x.P_.|
00000340  a1 20 60 d1 f2 52 0f ba  01 42 b9 99 31 7e 16 59  |. `..R...B..1~.Y|
00000350  5f ef b2 b4 f2 54 27 65                           |_....T'e|
00000358

**Comment by Foxboron** [comment]
`rm -rf /usr/share/secureboot` and reset your Secure Boot keys in the BIOS menu. You are running the OEM keys and don't have User Mode enabled.

**Comment by ShabirK21** [comment]
this is the output i get for sbctl status after removing and resetting the keys

Installed:      ✗ sbctl is not installed
Setup Mode:     ✓ Disabled
Secure Boot:    ✗ Disabled
Vendor Keys:    microsoft

**Comment by Foxboron** [comment]
How are you resetting the keys?

**Comment by ShabirK21** [comment]
In my BIOS, there is a option "reset to factory keys"

**Comment by Foxboron** [comment]
That's the wrong option. "Reset to factory keys" re-enrolls your OEM keys. You want to put it into "User Mode" and find "clear or all keys" or a similar option.

**Comment by ShabirK21** [comment]
ok i managed to do it

Installed:      ✗ sbctl is not installed
Setup Mode:     ✗ Enabled
Secure Boot:    ✗ Disabled

**Comment by Foxboron** [comment]
What kind of laptop is this?

**Comment by ShabirK21** [comment]
Lenovo legion

**Comment by Foxboron** [comment]
Right, you need to be specific. Please just use `--microsoft` if you are unsure.
