### ISSUE TITLE
Lenovo Thinkcentre M73 + Systemd-boot accepts keys but fails to verify

### ISSUE THREAD

**Issue by Lejaxak** [Foxboron/sbctl#121]
On Lenovo Thinkcentre M73 SFF (not Tiny device by same name) i5-4570.
With Arch Linux, Systemd-boot, UEFI booting only.
Using latest (FCKT99AUS) BIOS from Lenovo.

Steps performed:
sbctl create-keys
Reboot to UEFI
Reset Secure Boot keys in UEFI (Security > Secure Boot > Reset to Setup Mode)
Reboot
sbctl status reports Setup Mode enabled and Secure Boot disabled
sbctl sign -s /boot/EFI/BOOT/BOOTX64.EFI
sbctl sign -s /boot/EFI/systemd/systemd-bootx64.efi
Signed unified EFI kernel image with Dracut
sbctl enroll-keys --yes-... (sbctl reports no TPM log found, device has no dGPU, no opROMs to worry about)
sbctl enroll-keys finished without error.
Reboot
sbctl status reports Setup Mode, Secure Boot disabled
Reboot to UEFI
Enable secure boot (Security > Secure Boot > Enable Secure Boot)
Reboot
Device fails to boot, system reports "Secure Boot Violation. Invalid signature detected. Check Secure Boot policy in setup."

I have also attempted with 'sbctl enroll-keys --microsoft' for completion. Same result as not including vendor keys.

PK, KEK, db are all present in /sys/firmware/efi/efivars/

Outputs:
> sudo sbctl status
Installed:	✓ sbctl is installed
Owner GUID:	a8cd269b-467e-4ac4-ade9-414af4a41153
Setup Mode:	✓ Disabled
Secure Boot:	✗ Disabled

> sudo sbctl verify
Verifying file database and EFI images in /boot...
✓ /boot/EFI/BOOT/BOOTX64.EFI is signed
✓ /boot/EFI/systemd/systemd-bootx64.efi is signed
✓ /boot/EFI/Linux/linux-5.15.13-zen1-1-zen-24fbbad54d0940f3889953e4fa81774a-rolling.efi is signed

**Comment by Foxboron** [comment]
Hmmmmm. Weird. Output of `efibootmgr -v` please

**Comment by Lejaxak** [comment]
`BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0001,0002,0003,0004
Boot0000* Linux Boot Manager	HD(1,GPT,0a71f6db-2ca1-0b47-9d11-48f57794878e,0x800,0x64000)/File(\EFI\systemd\systemd-bootx64.efi)
Boot0001* UEFI: IP4 Realtek PCIe GBE Family Controller	PciRoot(0x0)/Pci(0x1c,0x5)/Pci(0x0,0x0)/MAC(4437e6dd0e43,0)/IPv4(0.0.0.00.0.0.0,0,0)..BO
Boot0002* UEFI: IP6 Realtek PCIe GBE Family Controller	PciRoot(0x0)/Pci(0x1c,0x5)/Pci(0x0,0x0)/MAC(4437e6dd0e43,0)/IPv6([::]:<->[::]:,0,0)..BO
Boot0003* Generic Usb Device	VenHw(99e275e7-75a0-4b37-a2e6-c5385e6c00cb)
Boot0004* CD/DVD Device	VenHw(99e275e7-75a0-4b37-a2e6-c5385e6c00cb)
`

**Comment by Foxboron** [comment]
Can you verify that you have mounted the ESP and isn't signing files on the harddisk itself?
Please give the output of `sudo blkid` and `mount`

**Comment by Lejaxak** [comment]
> sudo blkid
/dev/mapper/cryptroot: LABEL="Filesystem" UUID="f64b375f-dbb9-497f-9c7d-5d86037e0a39" UUID_SUB="093d6fed-8306-4363-8f6c-4cd27c272fc7" BLOCK_SIZE="4096" TYPE="btrfs"
/dev/sda2: UUID="d0f7d2b6-7c38-4310-87e8-2c73c8893d22" TYPE="crypto_LUKS" PARTUUID="9246f2b8-85be-534b-9ee9-2aa486551fcc"
/dev/sda1: LABEL_FATBOOT="ESP" LABEL="ESP" UUID="E807-A9F5" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="0a71f6db-2ca1-0b47-9d11-48f57794878e"


> sudo mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=3956712k,nr_inodes=989178,mode=755,inode64)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=1590800k,nr_inodes=819200,mode=755,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
/dev/mapper/cryptroot on / type btrfs (rw,relatime,lazytime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,autodefrag,subvolid=336,subvol=/@)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=31,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=528)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
/dev/mapper/cryptroot on /.snapshots type btrfs (rw,relatime,lazytime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,autodefrag,subvolid=339,subvol=/@snapshots)
/dev/mapper/cryptroot on /swap type btrfs (rw,relatime,lazytime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,autodefrag,subvolid=338,subvol=/@swap)
/dev/mapper/cryptroot on /home type btrfs (rw,relatime,lazytime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,autodefrag,subvolid=337,subvol=/@home)
/dev/mapper/cryptroot on /var/log type btrfs (rw,relatime,lazytime,compress-force=zstd:1,ssd,discard=async,space_cache=v2,autodefrag,subvolid=340,subvol=/@var_log)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=1048576,inode64)
/dev/sda1 on /boot type vfat (rw,relatime,lazytime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=795400k,nr_inodes=198850,mode=700,uid=1000,gid=984,inode64)

**Comment by Foxboron** [comment]
Okay, I have no clue :)

Can you enroll with the `microsoft` keys and see if you can boot a signed shim? Or if Windows boot from it?

Or could you try sign a new binary with `sbsign` instead and see if you have the same issues?

The idea here is to try see if there is a bug in the signing `go-uefi` does, or if this is a general firmware implementation issue.

**Comment by Lejaxak** [comment]
Alright, some findings from a little experimentation:
Manually signing BOOTX64.EFI and systemd-bootx64.efi with `sbsign` and enrolling user keys with `sbkeysync` produces the same boot failure as `sbctl` does.
Enrolling `--microsoft` keys with `sbctl enroll-keys` DOES allow booting of the Microsoft-signed shim perfectly fine with shim chaining to systemd-boot. `sbctl status` correctly reports Secure Boot Enabled and Microsoft vendor keys present in this scenario.

**Comment by Foxboron** [comment]
What happens if you take the `shim` from the `[community]` repository and sign that with `sbsign` and/or `sbctl`?

There have been reports of sb-boot producing invalid files. I wonder if just booting the EFISTUB through efibootmgr would work?

**Comment by Lejaxak** [comment]
Re-enrolled user keys through Setup Mode and `sbctl enroll-keys`. Signed a new unified kernel image and set up EFISTUB booting with `efibootmgr`. Results in the same Secure Boot violation.
I can try the same thing with `shim`, though I doubt the result would be any different.

**Comment by Foxboron** [comment]
Okay. I have no clue. This seems like faulty firmware where it doesn't actually enroll the secure boot keys. I have a hard time believing there is any issues with my code by sound of it.

I trippel checked signing a recent sd-boot bootloader and I can boot it just fine.  I'm not sure what else to do here.

**Comment by Lejaxak** [comment]
To be honest I completely agree with you here. If I have some time I might attempt enrolling the user keys `KeyTool` and see if that works. I had a suspicion it might be a buggy UEFI implementation since `sbctl` worked just fine on my other Lenovo machine a couple days ago. Thankfully the M73 doesn't _need_ Secure Boot, but I thought it might warrant being brought to your attention as it was such a strange issue.
Perhaps it may be worthwhile implementing a blacklist/warning list of devices with known/potentially buggy UEFI implementations to inform the user?
Feel free to close this issue, I'll probably update with results of attempting `KeyTool` and close it myself after.

**Comment by Foxboron** [comment]
I'd be interested knowing how KeyTool works for you. This might even be a kernel issue so removing that factor from it would be great.

I'm unsure how to properly detect or deny list invalid devices but we can make a feature request for that :)

**Comment by Foxboron** [comment]
Also, try `sbctl enroll-keys` (removing the microsoft vendor keys) and check if the signed shim is still bootable :)

**Comment by Lejaxak** [comment]
Removing Microsoft vendor keys and retaining signed shim renders the system similarly unbootable.
KeyTool only supports .esl and .cer files for KEK/db and .auth for PK so I created a new set of keys using the Archwiki's instructions. Signed systemd-boot and the unified kernel image with the new keys then rebooted to KeyTool. KeyTool allowed the insertion of new PK/KEK/db just fine, however when enabling Secure Boot after verifying the system was out of Setup Mode, the same issue of failing to validate the bootloader (or EFISTUB, or anything for that matter) persisted.
Honestly out of ideas on this one at this point. Seems the UEFI is validating Microsoft-signed EFI entries just fine when the Microsoft vendor keys are in-place, but failing to authenticate between the Secure Boot efivars and signed files.

**Comment by Foxboron** [comment]
There might be some obscure issues in the signing. But I don't think I'll spend time on it considering `sbctl` and `sbsign` results in the same behavior.

Thank you for the thorough testing and do feel free to submit other issues you find :)
