### ISSUE TITLE
errors importing existing keys

### ISSUE THREAD

**Issue by tpeacock19** [Foxboron/sbctl#125]
hello, I think there is an error here that has prevented me from importing my existing keys to sbctl. 

https://github.com/Foxboron/sbctl/blob/6f2bfac96ca8d20fe9706ecedb79e552a20c44cc/cmd/sbctl/import-keys.go#L107-L109

Using the following diff I was able to successfully import my keys. Is this meant to only read from the cert file?

```diff
diff --git a/cmd/sbctl/import-keys.go b/cmd/sbctl/import-keys.go
index 8cc63fb..4b6d54a 100644
--- a/cmd/sbctl/import-keys.go
+++ b/cmd/sbctl/import-keys.go
@@ -104,7 +104,7 @@ func RunImportKeys(cmd *cobra.Command, args []string) error {
 		if _, err := util.ReadCertFromFile(key.Cert); err != nil {
 			return fmt.Errorf("invalid certificate file")
 		}
-		if _, err := util.ReadKeyFromFile(key.Cert); err != nil {
+		if _, err := util.ReadKeyFromFile(key.Key); err != nil {
 			return fmt.Errorf("invalid private key file")
 		}
 		for src, dst := range map[string]string{
```

**Comment by Foxboron** [comment]
Ah yes, this seems like a copypaste error on my end :) Do you want to submit a pull-request with this fix? I should probably make a new release with this soon as well

**Comment by tpeacock19** [comment]
yes, no problem. I've made https://github.com/Foxboron/sbctl/pull/126

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/commit/e2c0d7b530404ecc413a70606e7bb06c73eb9364
