### ISSUE TITLE
Can't enroll keys

### ISSUE THREAD

**Issue by t0ssox** [Foxboron/sbctl#127]
I'm using ASRock B560 Steel Legend motherboard. I enabled Secure Boot in Setup Mode and cleared all keys. Now on fresh Arch Linux with rEFInd, I installed sbctl aswell. Keys created successfully but enrolling gives me error `measurement log didn't use sha1 or sha256 digests`.

> **sudo sbctl status**
Installed:      ✗ sbctl is not installed
Setup Mode:     ✗ Enabled
Secure Boot:    ✗ Disabled
> **sudo sbctl create-keys**
Created Owner UUID 5a0a506c-3862-47ee-bd03-03d4286024ca
Creating secure boot keys...✓ 
Secure boot keys created!
> **sudo sbctl enroll-keys**
measurement log didn't use sha1 or sha256 digests
> **sudo sbctl status**     
Installed:      ✓ sbctl is installed
Owner GUID:     5a0a506c-3862-47ee-bd03-03d4286024ca
Setup Mode:     ✗ Enabled
Secure Boot:    ✗ Disabled

**Comment by Foxboron** [comment]
Hmm, the code failing is the TPM Eventlog checking. Can you upload `/sys/kernel/security/tpm0/binary_bios_measurements` somewhere?

**Comment by t0ssox** [comment]
Okay I fixed that by enabling SHA-256 bank in TPM in UEFI BIOS. Now I have this warning:
```
Found OptionROM in the bootchain. This means we should not enroll keys into UEFI without some precautions.

There are three flags that can be used:
    --microsoft: Enroll the Microsoft OEM certificates into the signature database.
    --tpm-eventlog: Enroll OpRom checksums into the signature database (experimental!).
    --yes-this-might-brick-my-machine: Ignore this warning and continue regardless.
```

Which is weird because I used sbctl last year without any problems.

**Comment by Foxboron** [comment]
Yes, this is a recent thing and meant to be a bit more cautious when enrolling stuff. If you are confident you don't need any oprom circumvention you can use `--yes-this-might-brick-my-machine`
