### ISSUE TITLE
FR: add quiet output flag

### ISSUE THREAD

**Issue by augustozanellato** [Foxboron/sbctl#128]
Issue title is pretty self-explaining, I would do it myself if I knew Go.
Main use case I guess would be for the hooks in order to not pollute pacman logs and stdout.
The implementation should still print warnings and errors though.

Also thanks for the great work, using your project it has been a breeze to setup secure boot!

**Comment by RobertKwiatkowski** [comment]
I can try to do it. My idea is to add new flag inside logging.go and then use this flag in printing functions to check if they should print.
The flag would be able to somehow (I don't know yet how, I'm new to GO) passed by command line arg like --quiet or -q.

Please tell me yours opinions about this way to implement the feature.

**Comment by Foxboron** [comment]
>I can try to do it. My idea is to add new flag inside logging.go and then use this flag in printing functions to check if they should print.
>The flag would be able to somehow (I don't know yet how, I'm new to GO) passed by command line arg like --quiet or -q.

You could do something like this:
https://github.com/Foxboron/sbctl/blob/a3c537b77a4ede2e3056a0cc1a34fae15421d6c8/cmd/sbctl/main.go#L50-L52

I'm a little bit unsure how to make this super pretty with the fact I have two output modes and we want some filtering in the logging module for standard output and errors.

**Comment by augustozanellato** [comment]
Maybe the better way would be to implement the concept of log level instead of printOn/printOff. 
The basic idea behind that is having an enum with the possible levels and print a message only if it’s log level is >= current log level. Also making warning and error levels print to stderr rather than stdout would probably make things easier (or at least I think so, haven’t looked too deep into the json out format)

**Comment by Foxboron** [comment]
Yeah, you could just do logging level checkings inside the print functions :)

https://github.com/Foxboron/sbctl/blob/a3c537b77a4ede2e3056a0cc1a34fae15421d6c8/logging/logging.go#L49-L51

Errors should already head for stderr but there might be some more cleaning that I'd need to do.

**Comment by RobertKwiatkowski** [comment]
That was my initial idea, to add new flag and add checks inside print functions for this flag.
However this solution definitely isn't clean. At this moment I see two possibilities:
1. Add those bad looking checks and refactor it in the future.
2. Keep thinking about better way to do it.

I believe it depends if this feature is anyhow important to the project.

**Comment by Foxboron** [comment]
This entire project is a exercise in "lets do something ugly and refactor later" :) I don't mind having 1 now and 2 somewhere down the line. I'm not going to be super picky really.

**Comment by RobertKwiatkowski** [comment]
Ok then, today probably I won't have enough time, but tomorrow/at Friday I can try to implement this feature :).
