### ISSUE TITLE
Passing kernel options

### ISSUE THREAD

**Issue by Xenfo** [Foxboron/sbctl#144]
Is there a way to pass these kernel options `root=UUID=<UUID> rw nvidia-drm.modeset=1 loglevel=3 quiet`?

**Comment by Foxboron** [comment]
If you are using the kernel images `sbctl` generates you can include them inn  the file you specified. Most likely `/etc/kernel/cmdline`

**Comment by Xenfo** [comment]
```
❯ sudo cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-linux root=UUID=1f16e8ec-b73e-4b33-9be2-842b89cf0df0 rw nvidia-drm.modeset=1 loglevel=3 quiet

❯ sudo sbctl list-bundles
Enrolled bundles:

/boot/EFI/Linux/Arch-linux.efi
        Signed:         ✓ Signed
        ESP Location:   /boot
        Output:         └─/EFI/Linux/Arch-linux.efi
        EFI Stub Image:   └─/usr/lib/systemd/boot/efi/linuxx64.efi.stub
        Cmdline:            ├─/proc/cmdline
        OS Release:         ├─/usr/lib/os-release
        Kernel Image:       ├─/boot/vmlinuz-linux
        Initramfs Image:    └─/boot/initramfs-linux.img
        Intel Microcode:      └─/boot/intel-ucode.img
```
Does this mean I already have those kernel options?

**Comment by Foxboron** [comment]
Yep, that looks correct. It would be better to have `cmdline` point too `/etc/kernel/cmdline` as you can more easily customize the parameters.

**Comment by utku-helvaci** [comment]
@samchouse does nvidia drm work for you? for me it doesn't seem to get loaded. using nvidia-dkms
`sudo cat /sys/module/nvidia_drm/parameters/modeset`

**Comment by samchouse** [comment]
I stopped using this a while ago since I don't need secure boot anymore so I've got no idea
