### ISSUE TITLE
Add a wiki page for setting up Linux/Windows dual boot with Bitlocker

### ISSUE THREAD

**Issue by saligrama** [Foxboron/sbctl#146]
As you requested on [Reddit](https://old.reddit.com/r/archlinux/comments/ug9pu0/sbctl_how_do_i_use_it_to_with_a_windowsarch_linux/i7002rf/), I took some steps from a [blog post](https://saligrama.io/blog/post/upgrading-personal-security-evil-maid/#enrolling-your-key-into-secure-boot) I recently made and created a wiki page for setting up a Windows dual boot where Bitlocker does not keep reprompting for a recovery key. 

It would be great if you could add it to the wiki (or give feedback before doing so). I've attached the file here.

[DualBootBitlocker.md](https://github.com/Foxboron/sbctl/files/8633585/DualBootBitlocker.md)

**Comment by Foxboron** [comment]
Included the page here; https://github.com/Foxboron/sbctl/wiki/Linux-Windows-Dual-Boot-with-Windows-Bitlocker
