### ISSUE TITLE
Interaction between "Option ROM" hash and fwupd

### ISSUE THREAD

**Issue by VannTen** [Foxboron/sbctl#149]
The FAQ mentions that [we can enroll the checksums of firmware usually signed by
the microfost CA](https://github.com/Foxboron/sbctl/wiki/FAQ#option-rom).

What happen if the firmware is upgraded, for example with fwupd ? I'd presume
the checksum would need to be updated but maybe I'm missing something (like:
it's not the same firmwares we're talking about ?).

**Comment by Foxboron** [comment]
The checksum would likely change. So you would need to disable Secure Boot. I *think* this can be done with a simple `sbctl reset` before doing a fwupdmgr update. Then you can do `sbctl enroll-keys --tpm-eventlog` when you have rebooted.  But I would probably just try that before using `fwudpmgr`.

**Comment by Foxboron** [comment]
Now followup so considering this solved.
