### ISSUE TITLE
is sbctl compatible with Debian based distributions?

### ISSUE THREAD

**Issue by rbutera** [Foxboron/sbctl#150]
Linux newbie here, I've been using `sbctl` with an Arch-based install but thinking of moving over to Ubuntu/Pop! for the gentler learning curve.

The documentation refers to using `pacman` to install and there's an issue here (#119) which explicitly references `pacman` - so I have a bit of a stupid question - can you use `sbctl` on debian-based distributions?

**Comment by Foxboron** [comment]
It should be noted that Ubuntu and Pop (i think) have working Secure Boot through their shim setup, so `sbctl` isn't strictly needed.

However, `sbctl` is not packaged on Ubuntu/Debian/PopOS, so you would have to manually build this project and figure out the missing hooks to ensure your files are signed when Debian updates their initramfs. Feel free to provide the source for anything you figure :)

**Comment by rbutera** [comment]
Thanks for your reply and advice, @Foxboron 

A few of us are using `sbctl` to successfully sign [Opencore](https://dortania.github.io/OpenCore-Install-Guide/) in addition to Linux files in order to run MacOS on non-Apple hardware with SecureBoot / TPM enabled.

Your project has been the single best thing for us to make that process a lot less painful, so thank you so much for creating it.

I will close this issue, but I have one last question, as I intend to re-install Linux from Arch the 'proper' way in order to build an understanding of what's going on.

I have signed many efi binaries using the keys sbctl created and enrolled, and so I intend to back those up by packaging the entire contents of `/usr/share/secureboot` into a `tar` file and copy it to an external drive prior to reinstalling a fresh copy of Linux. 

Will `sbctl` behave nicely if I install `sbctl` on the new Arch install and then insert the backup into `/usr/share/secureboot`? 

Looking at the source I noticed that there is an `--import-keys` flag but I'm not sure if the GUID etc are significant.

**Comment by Foxboron** [comment]
The GUIDs are not significant beyond recognizing signature lists. You should in theory be able to unpack the entirety of `/usr/share/secureboot` and just issue `sbctl enroll-keys` to finish the install.

Super cool that you are using `sbctl` for this as well :)
