### ISSUE TITLE
Bootloader time disappears in systemd-analyze when using sbctl bundles

### ISSUE THREAD

**Issue by Samisafool** [Foxboron/sbctl#154]
Distro is btw

The bootloader time works when using kernel EFISTUB, but with sbctl bundles:

```
$ systemd-analyze
Startup finished in 1.517s (kernel) + 8.358s (userspace) = 9.876s 
graphical.target reached after 7.944s in userspace.
```

It does not account for the bootloader time.

What does sbctl use for the bundles? Why not efistub?

**Comment by Samisafool** [comment]
Looking at the code, it uses systemd-boot stubs. Considering that both -boot and -analyze are by systemd, they should support each other. So this must be sbctl's fault right?

**Comment by Samisafool** [comment]
Upd: now it shows:

```
$ systemd-analyze
Startup finished in 874ms (kernel) + 23.681s (initrd) + 3.850s (userspace) = 28.406s
graphical.target reached after 3.836s in userspace.
```

Why is it showing initrd now? (Note: I did not enter the password for a bit, that's why it is slow). I assume it's because I did full disk encryption and added systemd hook to initrd?

**Comment by Foxboron** [comment]
This isn't a sbctl issue and there isn't enough information here to figure out what is going on.

**Comment by Samisafool** [comment]
Right,

So if I use systemd-boot, the fw time and bootloader time is there.

https://systemd.io/BOOT_LOADER_INTERFACE/

Looks like it needs to implement this:

```
If LoaderTimeInitUSec and LoaderTimeExecUSec are set, systemd-analyze will include them in its boot-time analysis.
```

So, either a systemd-stub issue or an sbctl issue.

Still don't know about the fw time

**Comment by Foxboron** [comment]
Yes, and if you don't have a bootloader setting those options then there is nothing to infer. This isn't something `sbctl` is dealing with, it's not a bootloader.
