### ISSUE TITLE
Include extra firmware in bundle

### ISSUE THREAD

**Issue by potatoattack** [Foxboron/sbctl#161]
I would like to include the `i915-firmware.cpio.xz` firmware along with `intel-ucode.cpio`  (AUR: [intel-ucode-clear](https://aur.archlinux.org/packages/intel-ucode-clear)) together in a bundle.
Is there a way to achieve this?

If not, consider this a feature request.

Thanks!

**Comment by Foxboron** [comment]
Use the Unified Kernel Image support in either `mkinitcpio` or `dracut` instead of `sbctl` I think. I'm not sure if I'll implement support for multiple initrds beyond the current switches.

**Comment by potatoattack** [comment]
I ended up making a unified image with `mkinitcpio` and signing it with `sbctl` and it works great.
Thanks for the advice.

**Comment by IPlayZed** [comment]
> I ended up making a unified image with `mkinitcpio` and signing it with `sbctl` and it works great.
> Thanks for the advice.

I think this should be the accepted way as this provides maintainibility for sbctl.

I think this issue could be closed.

**Comment by Foxboron** [comment]
No doing new features in the UKI support
