### ISSUE TITLE
Can't boot in secure boot mode even after signing files with sbctl

### ISSUE THREAD

**Issue by carretinha** [Foxboron/sbctl#162]
Hi! I was trying to setup secure boot with windows in dual boot. And I used sbctl for that, but I've made some mistakes.

First (rookie) mistake: I installed it, and than notice some updates, than I updated. But some of the packages must have trigger the pacman hook and it tried to re-sign the files before I created keys or anything. But it seemed to not affect the process much.

Second mistake: I wasn't in setup mode when I created the keys. After correcting my mistake I try to redone all the steps (but it won't create new keys), proper enrolled the keys using --microsoft param and everything worked as expected.

Files that I signed (which is all of those who shows in sbctl verify):

✓ /boot/EFI/BOOT/BOOTX64.EFI is signed
✓ /boot/grub/x86_64-efi/core.efi is signed
✓ /boot/grub/x86_64-efi/grub.efi is signed
✓ /boot/vmlinuz-linux is signed

Except that when I reboot, and activate secure boot, it shows the red block [like this one](https://www.thewindowsclub.com/wp-content/uploads/2019/09/Invalid-signature-detected.jpg), than proceed to use Windows Bootloader, and successfully boot on Windows.

Can I make something so I can fix the process through sbctl? Or should I use one of the other methods on the wiki? In the case of the second one is it safe to remove sbctl? It it is, using pacman -R sbctl is enough or should I use other command? I also use Nvidia proprietary driver, could be it?

Also [asked for help in Reddit](https://www.reddit.com/r/archlinux/comments/woazap/cant_boot_in_secure_boot_mode_even_after_signing/) and there's some trials and results:
Was suggested that I should create a Unified Kernel Image. I've generated it! But didn't work. Even after enrolling its keys. But also grub didn't indexed it automatically, so I added the entry manually, but also didn't work.

Thought it might be grub, so I installed Refind with local keys, remove all entries that were not the Arch Unified Kernel Image and Windows; signed its EFI, using sbctl, and also didn't work.

Right now there are those files in /boot all signed:

Verifying file database and EFI images in /boot...
✓ /boot/EFI/Linux/archlinux-linux.efi is signed
✓ /boot/EFI/refind/refind_x64.efi is signed
✓ /boot/grub/x86_64-efi/core.efi is signed
✓ /boot/grub/x86_64-efi/grub.efi is signed
✓ /boot/vmlinuz-linux is signed
✓ /boot/EFI/BOOT/BOOTX64.EFI is signed
✓ /boot/EFI/Linux/archlinux-linux-fallback.efi is signed

**Comment by Foxboron** [comment]
Please post information about the machine you are attempting this on.

**Comment by carretinha** [comment]
Thanks for responding so quickly! That's all basic information about the system:

Manufacturer: Dell Inc.
Product Name: XPS 8700
Processors: 8 × Intel® Core™ i7-4790 CPU @ 3.60GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2

It's a PC; it does not have TPM support; and I updated Bios before starting arch installation process. Do you need something more specific?

**Comment by Foxboron** [comment]
It's from 2013 so I wouldn't be terribly surprised if this has some extremely terrible UEFI firmware on it. I'm sadly not sure what the issue could be.

**Comment by carretinha** [comment]
Oh, I understand, thanks anyway.
