### ISSUE TITLE
Lenovo Thinkbook 14 iml

### ISSUE THREAD

**Issue by niksingh710** [Foxboron/sbctl#166]
sbctl enroll-keys -m
Enrolling keys to EFI variables...
With vendor keys from microsoft...✗ 
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f: permission denied

when switching to setup mode then it enrolls but says secure boot disabled in status.

tried deleting keys from BIOS too.

**Comment by Foxboron** [comment]
You need to re-enable secure boot after enrolling it with setup mode.

**Comment by niksingh710** [comment]
> You need to re-enable secure boot after enrolling it with setup mode.

Thanks for the response I figured it out.
and had to disable shim in grub to find that from issues 

adding these all as a base guide will be helpful for someone coming as expecting sbctl as a easier way to setup.

**Comment by Foxboron** [comment]
The github README is not a guide though. It's a demonstration of the functionality. The usage guide can be found in the manpage :)

https://man.archlinux.org/man/sbctl.8#USAGE

If you feel anything is missing here feel free to send a patch or point them out.

**Comment by niksingh710** [comment]
Closing this as i had to put my bios in setup mode to enroll keys and had to add modules list in grub

`sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB --modules="[Modules](https://gist.github.com/niksingh710/7982292b88f3cab444d8f04b1e88468a)" --disable-shim-lock`
