### ISSUE TITLE
Please provide a package for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by IPlayZed** [Foxboron/sbctl#167]
Hi!

It would be nice if you could package (or provide build instructions) for Ubuntu 22.04 LTS.

**Comment by Foxboron** [comment]
I don't really want to learn deb packaging so someone would need to provide this.

**Comment by IPlayZed** [comment]
How do I build on Arch?

I would be willing to look into packaging it for deb if I know a bit more.

**Comment by klausenbusk** [comment]
Please check out the PKGBUILD: https://github.com/archlinux/svntogit-community/blob/packages/sbctl/trunk/PKGBUILD.

**Comment by dngray** [comment]
Maybe someone might like to take a look at https://wiki.debian.org/RFP. I'm currently working on getting this into Fedora.

**Comment by IPlayZed** [comment]
It would be great if this was streamlined across distros, it is only tool providing a good implementation for secure boot management imho. The problem with shims is that they do not solve the problem of unsigned initramfs images, which result in a lax interpretation of what is trusted, so if you want to be 100% compliant in corporate, you have to make sure to generate your own EFI bundles and sign them manually. This tool provides that.

**Comment by Foxboron** [comment]
People are free to contribute packages to their respective distributions, but this is not something I'll be pushing for personally as I lack the time for it.

For a list of existing packages please see repology. https://repology.org/project/sbctl/versions

Could probably mention this on the README as well.

**Comment by IPlayZed** [comment]
Please don't misunderstand my comment @Foxboron  I am not pushing you personally, this is just a discussion.

**Comment by Foxboron** [comment]
No worries :) It's just a general statement from my side.

**Comment by sbskas** [comment]
As a matter of fact, when I need to be cross-compatible with different distro, I use fpm to convert packages from one package format to another one.
It may be of some help to automically convert packages or to generate basic packages skeletons.

**Comment by jloeser** [comment]
I needed it too and built it on openSUSE Build Service.

You can install it via:
```
root@vm:~# . /etc/os-release
root@vm:~# wget https://download.opensuse.org/repositories/home:/jloeser:/secureboot/xUbuntu_$VERSION_ID/Release.key -O- | apt-key add -
root@vm:~# add-apt-repository -y "deb https://download.opensuse.org/repositories/home:/jloeser:/secureboot/xUbuntu_$VERSION_ID/ ./"
root@vm:~# apt update
root@vm:~# apt install sbctl
root@vm:~# sbctl status
Installed:	✓ sbctl is installed
Owner GUID:	f192ece2-c80e-4cb4-acbd-c3e22a63ead7
Setup Mode:	✓ Disabled
Secure Boot:	✓ Enabled
Vendor Keys:	microsoft
```
OBS project is here: https://build.opensuse.org/project/show/home:jloeser:secureboot (thanks to original packager)

**Comment by Foxboron** [comment]
A package request has been made in Debian.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030845

**Comment by Foxboron** [comment]
@jloeser if you intend to keep the repo updated then I won't mind adding install instructions for your OBS repo to the `README.md` file.

**Comment by jloeser** [comment]
> @jloeser if you intend to keep the repo updated then I won't mind adding install instructions for your OBS repo to the `README.md` file.

Sure, go for it.

**Comment by Foxboron** [comment]
There is now a Debian package that needs to be maintained. As some movement has happened I'll just close this issue and this isn't actionable for me.

https://salsa.debian.org/go-team/packages/sbctl
