### ISSUE TITLE
Please document how the Pacman hook works.

### ISSUE THREAD

**Issue by IPlayZed** [Foxboron/sbctl#168]
Hi!

I was looking to update the Arch wiki article on SB to include sbctl as an actually viable automated strategy on maintaining an SB system.

However without diving into the code, I could not find any documentation on how the pacman hooks are generated.

Could you please provide some documentation on how that works?

**Comment by Foxboron** [comment]
It's an implementation detail under `contrib/`. Nothing to document really.

https://github.com/Foxboron/sbctl/blob/master/contrib/pacman/ZZ-sbctl.hook

**Comment by IPlayZed** [comment]
Thanks!

I was just not sure exactly where to look.

**Comment by neitsab** [comment]
I was about to open an issue to suggest mentioning the existence of the pacman hook (and maybe the kernel-install one as well) in the README, so that users are aware of this crucial feature!

I recommand adding at the end of the Signatures section something along the lines of:

> After a file has been added to the sign database with `-s`, it will be automatically re-signed every time pacman installs/upgrades/removes a file in `/boot/*`, `efi/* ` and a few other directories. See `contrib/pacman/ZZ-sbctl.hook` for details.

What do you think?
