### ISSUE TITLE
Add wiki article for HPE servers

### ISSUE THREAD

**Issue by appletalk** [Foxboron/sbctl#170]
I tried to figure out how to open a PR against a wiki page but I was not able to. If there is a better way to send this over, please let me know.
I wrote a wiki page outlining the steps I used to enable Secure Boot on an HPE DL380 Gen 9 server without a TPM. It likely applies to most HPE server products. Unlike other devices they need an HPE db key, I'm guessing to load an option rom related to the storage controller. The Microsoft keys were not required.

It might need some cleanup/rewording and it's possible there is a better way to accomplish some of the steps. I'm open to whatever you think is best.

Find the document here.
https://github.com/appletalk/sbctlwiki/blob/hpe-server-db-key/HPE-Server-Include-Factory-DB-Key.md

**Comment by Foxboron** [comment]
Thanks!
Made the wiki page here :)

https://github.com/Foxboron/sbctl/wiki/HPE-Server-include-factory-db-key

Sorry for the delay!

**Comment by appletalk** [comment]
Awesome, thanks!  I hope its helpful to others.
