### ISSUE TITLE
Unable to enroll keys for strange "permission denied" reason

### ISSUE THREAD

**Issue by ItachiSan** [Foxboron/sbctl#171]
Hi everyone,

I am currently experimenting with `sbctl` in order to be able to sign binaries to boot.
As of now I have been using a quite old and outdated version of PreLoader and I wanted to either use a newer version signed with my own keys or switch to Shim and properly sign Grub and kernel for everything to be fine.

I have created my own keys via `sudo sbctl create-keys` but I am having trouble enrolling them, as you can see from the below output:

```sh
 giovanni  ~  Projects  OBS  telegram-desktop-dev  sbctl status
Installed:      ✓ sbctl is installed
Owner GUID:     ba2c48b3-7545-41fa-bc29-d2a091709a1a
Setup Mode:     ✓ Disabled
Secure Boot:    ✓ Enabled
Vendor Keys:    microsoft
 giovanni  ~  Projects  OBS  telegram-desktop-dev  sudo sbctl enroll-keys --microsoft
[sudo] password for giovanni:
!! File is immutable: /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c
!! File is immutable: /sys/firmware/efi/efivars/KEK-8be4df61-93ca-11d2-aa0d-00e098032b8c
!! File is immutable: /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f
You need to chattr -i files in efivarfs
 giovanni  ~  Projects  OBS  telegram-desktop-dev  1  sudo chattr -i /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c /sys/firmware/efi/efivars/KEK-8be4df61-93ca-11d2
-aa0d-00e098032b8c /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f
 giovanni  ~  Projects  OBS  telegram-desktop-dev  sudo sbctl enroll-keys --microsoft
Enrolling keys to EFI variables...
With vendor keys from microsoft...✗
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f: permission denied
 giovanni  ~  Projects  OBS  telegram-desktop-dev  1 
```

Any tip on how to proceed? I can provide any information you need.

**Comment by Foxboron** [comment]
<pre>
Setup Mode:     ✓ Disabled
Secure Boot:    ✓ Enabled
</pre>

You need to turn off Secure Boot, set it to user mode (or remove existing keys), then use sbctl. Currently you have Secure Boot enabled and `sbctl` can't do anything about that.

**Comment by wax0n** [comment]
I have the same problem, any idea?

<sup>❯ sbctl status
Installed:	✓ sbctl is installed
Owner GUID:	bd764742-0d6c-4d80-9728-619f29a0b6be
Setup Mode:	✓ Disabled
Secure Boot:	✗ Disabled
Vendor Keys:	microsoft
❯ sbctl enroll-keys --microsoft
Enrolling keys to EFI variables...
With vendor keys from microsoft...✗ 
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f: permission denied</sup>

**Comment by Foxboron** [comment]
You are not in `setup mode`. Please check your BIOS settings.

**Comment by ItachiSan** [comment]
I thought from the previous comment we were supposed to be in user mode and with Secure Boot off...?
I am in such situation, I can take some pictures of it if needed

**Comment by Foxboron** [comment]
You need to also be in SetupMode. Getting that enabled depends on the manufacturer.

**Comment by medhefgo** [comment]
To enter setup mode you need to delete the platform key (PK) in the firmware setup. It's not always enough to disable secure boot (or set it to custom mode). It's usually in a submenu for managing secure boot keys.

**Comment by Foxboron** [comment]
@medhefgo I plan on adding a very basic check in sbctl before we try enrolling keys. It would probably help a bit on the UX.

**Comment by medhefgo** [comment]
It would also help if the manpage were correct. It currently says to put the device into "User mode" in the usage section.

Also, in principle you don't have to disable secure boot. All that should be needed is removing/clearing the PK to put it in setup mode and thus, automatically disabling secure boot. This also ought to have the benefit of not needing another visit to the firmware to re-enable secure boot after enrolling as it *should* automatically turn on once the PK var is written. At least that's how the enrollment works in sd-boot.

**Comment by medhefgo** [comment]
My firmware actually lets me make proper screenshots of the firmware UI. If you're interested, I can provide you with some screenshots to demonstrate the workflow to novice users.

**Comment by Foxboron** [comment]
Yes please! The main issue has been to try and describe the workflow by mostly guessing the layout in the BIOS menu. It's not easy and at best confusing :)

>It would also help if the manpage were correct. It currently says to put the device into "User mode" in the usage section.

Oh, right. I should fix that as well.

**Comment by ItachiSan** [comment]
I would also suggest to update the correct value in the script.
It currently writes that it is "god" to have Setup Mode disabled.

From my previous log (redacted for clarity):
```shell
$ sbctl status
...
Setup Mode:     ✓ Disabled # <-- Here
...
```

**Comment by ItachiSan** [comment]
Ok, it works, with the following:

1. Go in UEFI settings
2. Put the firmware in Setup Mode (no need to turn off Secure Boot)
3. Reboot in your Linux OS
4. Re-do the `sbctl enroll-keys`

I feel the guides and the app should say clearly that it needs Setup Mode for the whole `enroll-keys` to work.
I will try to enroll my own keys manually too to see if that is also feasible.

**Comment by cbrnr** [comment]
I have the same issue, but I don't know how to enable "setup mode". The UEFI has settings related to Secure Boot described here: https://www.dell.com/support/manuals/de-at/latitude-15-5501-laptop/latitiude_5501_setupspecs/secure-boot?guid=guid-8a811805-1bb4-4d27-a2e8-ef6a333be1a9

Any ideas what I need to set in order to enroll the keys? I am hesitant to just play around and delete keys because I might brick the computer.

**Comment by medhefgo** [comment]
> Any ideas what I need to set in order to enroll the keys? I am hesitant to just play around and delete keys because I might brick the computer.

From looking at the manual you have to enable custom mode (I wouldn't know how from the manual) (this differs from ASUS firmware where custom mode means something else?) and then use expert key management to delete all keys. Deleting all keys should always be safe to do as the firmware is supposed to enter setup mode after, which disables any signature enforcement.

Also, if your firmware lets you make screenshots too, I would like to get my hands on some.

**Comment by cbrnr** [comment]
Alright, thanks @medhefgo I'll try that. Just to be sure, I have a Windows installation with Bitlocker on my other SDD – deleting the keys will not impact that either, right? I'm assuming that Microsoft bootloader signatures are always available.

I can try and see if I can make screenshot. I'll report back next week.

**Comment by medhefgo** [comment]
Enrolling custom secure boot keys will change the TPM measurement that bitlocker uses to automatically unlock the device. So you will need to have your recovery key at the ready.

**Comment by medhefgo** [comment]
Also, you should pass the `--microsoft` option when enrolling keys with sbctl, as clearing the secure boot keys will remove microsoft keys.

**Comment by cbrnr** [comment]
Thanks, I will do that!

**Comment by cbrnr** [comment]
Thanks @medhefgo, deleting all keys worked! Unfortunately, I didn't find a way to take screenshots within the UEFI though. I could take a "real" picture if you want, not sure if that's what you really want/need.

**Comment by Foxboron** [comment]
Output of `xxd /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c` please

**Comment by Gravydigger** [comment]
Certianly, and thanks for the quick responce!
```
[root@gravyArch ~]# xxd /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c
[root@gravyArch ~]#
```
There was no output provided. I also tried to see if `chattr -i /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c` did anything, but the output was the same.

**Comment by Foxboron** [comment]
Can you reset your keys from the BIOS menu again and retry?

**Comment by Gravydigger** [comment]
```
[root@gravyArch ~]# sbctl status
Installed:      ✓ sbctl is installed
Owner GUID:     e7b28036-69e6-4bda-b63f-15fa7cc2a4c7
Setup Mode:     ✗ Enabled
Secure Boot:    ✗ Disabled
[root@gravyArch ~]# sbctl enroll-keys -m
Enrolling keys to EFI variables...
With vendor keys from microsoft...✗ 
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c: permission denied
```
As a sanity check, here's my secure boot config:
![IMG_20230315_221015_107](https://user-images.githubusercontent.com/53815736/225300093-3fb5d4a9-cb44-403f-8a86-d8438e0e1541.jpg)

**Comment by Foxboron** [comment]
What sort of laptop is this?

**Comment by Gravydigger** [comment]
Lenovo Thinkpad Yoga 260. Would you like the output of `hwinfo --short`?

**Comment by medhefgo** [comment]
Generally, you need to enable secure boot to be in setup mode (as strange as that sounds). Unless the firmware won't let you delete the PK without disabling it.

**Comment by Gravydigger** [comment]
I enabled secure boot in the UEFI, and loaded back into Arch. However, the result is the same. Running `bootctl` gets me following line:
```
[root@gravyArch ~]# bootctl
...
Secure Boot: disabled (setup)
...
```
Maybe it automactially disables Secure boot until Setup mode is disabled?

**Comment by medhefgo** [comment]
That output is expected. You cannot have secure boot active without a PK. My expectation is that enrollment should now work though: Reading the manual for your laptop, secure boot should be enabled, then reset to setup mode should be used, which should put platform mode to setup and secure boot mode to custom.
If enrollment still does not work you should try clearing all secure boot keys. It might be that the firmware refuses PKs if not all databases are fully trusted by it (the dbx would be signed by the MS KEK and that sbctl feature hasn't seen a release yet I think?).

**Comment by Gravydigger** [comment]
So I did the following:
I went into the UEFI, and Restored factory keys (try try again from a clean slate), then I pressed "Reset to Setup Mode". I logged into Arch and tried `sbctl enroll-keys -m`, with no luck. I restarted and entered the UEFI again, pressed "Clear all secure boot keys", went back into Arch and tried the command again with no luck :/

Would it be likely that at this stage, sbctl would not support my hardware currently? I am using lvm2 & luks to encrypt the drive and I have a seperate boot partition, so I'm not sure if that would mess anything up in regards to how `sbctl` would work?

**Comment by medhefgo** [comment]
Have you tried clearing the keys with secure boot disabled too (not that I expect that to work)?

What I find odd here is that it fails writing the PK, while it accepts the db and KEK just fine…

After clearing all keys, do any of these exist and if so, what does `hexdump -C` show (none of these should exist at this point):
```
ls -1 /sys/firmware/efi/efivars/{db,dbx,KEK,PK}-*
```

What you can also try is using systemd-boot for enrolling. The instructions for creating the keys and variables are in `man loader.conf` (just copy the `*.auth` files to `$ESP/loader/keys/sbctl/`).

**Comment by Gravydigger** [comment]
After clearing the keys (with or without secure boot disabled), running the command shows that no keys exist.
As for systemd-boot, I'll get back to you if that works. I do have GRUB installed, so should I expect any issues regarding using systemd-boot?

**Comment by mfgbhatti** [comment]
I am using dell inspiron 7570 with bios version 1.25.0, kernel 6.3.8-arch1-1 and operating system arch.
In dell inspiron bios, there is secure boot tab, and underneath there is another option which is **Custom Key Management**. It gives you option to save existing keys to file, as well as load custom keys. But there are two buttons one with reset keys and other one delete keys. For sbctl you need delete keys and it will delete all. If you are on dell and the bios is same. You can get rid of this error by going through these steps

1. Check above option and you suppose to leave it **checked**. Otherwise it will reset your keys.
2. Deleting you keys in this option will give you **"Setup Mode"** for sbctl. After deleting your keys, you are set.
3. Restart.
4. In your operating system, follow the read me, and go through status, creation, enrol, sign. 

If you are not creating and enrolling, you have to go through step 2, 3 and 4.

I encounter this problem because my system was not in setup mode. And I issued create-keys. I have to restore my previous snapshot to redo everything above.

**Comment by marek-rychly** [comment]
I have the same laptop as @Gravydigger, that is Thinkpad Yoga 260, and there is the same issue: Secure Boot in Setup Mode with clean key-slots (BIOS action "Clear All Secure Boot Keys" and "Switch to Setup Mode") and "sbctl enroll-keys" (both with and without --microsoft) is reporting "couldn't write efi variable" for PK (and according to strace, it seems that it could not write also other vars). It is strange that before the enrollment, "sbctl status" is reporting "Vendor Keys: none" and after the unsuccessful enrollment, it is "Vendor Keys: microsoft". So it seems that something was successful but still it reported the error, there is nothing in the PK var (empty hexdump), and Setup Model is still active (also after reboot). I tried the enrollment both with enabled and disabled Secure Boot (always in Setup Mode).

**Comment by medhefgo** [comment]
@marek-rychly Does manipulating efivars work in general? Try changing/adding boot options with efibootmgr and see if they persist across boots. Also, check the kernel logs for efivar/efi runtime issues.

Also, as suggested by me earlier, you could try enrolling keys with systemd-boot to rule out format issues.

**Comment by AkechiShiro** [comment]
I'm running into this issue as @marek-rychly described however in a virtual machine running in QEMU with NixOS and Lanzaboote, is there any way I can debug, the permission denied issue ?
Any pointers on how to move forward with this issue ?

Maybe getting to the bottom of this issue, could improve sbctl as a whole, if there is any way I can help on that front, I will definitely try to.

**Comment by Foxboron** [comment]
Which version is this?

**Comment by Foxboron** [comment]
Also, please make sure the keys are properly reset.

**Comment by AkechiShiro** [comment]
Hi @Foxboron this is version 0.12 for sbctl.

How can I make sure the keys have been reset properly ? The only thing I know is that I did reset them in Tianocore BIOS interface.

**Comment by Foxboron** [comment]
Please update to 0.13 and recreate the keys. Please check if it solves the issue. Else ill fix my tanocore integration suite to check this. Generally everything here has been tested towards tianocore

**Comment by AkechiShiro** [comment]
I did retry with 0.13 and it is still an issue, I can also add that after running 3 times sbctl --enroll-keys, the 4th time, the error changes from permission denied to no space left on device.

I added the --yes-brick-my-machine option because sbctl was warning about OptionRoms as this is a qemu VM, I don't care if it bricks the VM.

When looking into the BIOS, there are keys that are KEK(2 objects), DB (3 signatures), the PK is empty (as it was permission denied)

Resetting the secure boot keys/cleaning the databases, allows me to retrigger this weird error.

So when running sbctl --enroll-keys --microsoft --yes-brick-my-machine

**Comment by Foxboron** [comment]
> So when running sbctl --enroll-keys --microsoft --yes-brick-my-machine the db gets filled when the permission is denied for the PK efivars

The "no space left on device" is because we keep appending new signature lists to the database and you exchaust the space of the efi nvram. Generally it should not be appended and truncated at *some* point. But I guess this is something i should fix as well.

**Comment by AkechiShiro** [comment]
Yes but there are multiples issues (at least 2) :

- Mainly, why PK is not writable to (I have also used the `efi_no_storage_paranoia` kernel parameter, that didn't help)
- The appending of multiples signatures is probably due to the --yes-brick-my-machine but I guess it's more clean to handle the case by truncating as you recommended.

I still can't find why the permission to the PK is denied but there must be something wrong with my setup VM.

**Comment by AkechiShiro** [comment]
@Foxboron 

I might have found the issue with the permission denied on my end (I still didn't pinpoint it exactly) but it could be upstream (in edk2) I need to further investigate.

**Comment by Foxboron** [comment]
It's a bit hard to debug these sort of issues, so having one issue with a perpetual help thread isn't super useful for me. Feel free to open discussion threads for specific hardware things, but I can't really help out on those.
