### ISSUE TITLE
Attempting to sign "memtest.efi" from Memtest86+-efi Arch Extra package triggers "slice bounds out of range"-error

### ISSUE THREAD

**Issue by WinterStar2** [Foxboron/sbctl#175]
Doing: "sbctl sign -s /boot/memtest86+/memtest.efi -o /efi/EFI/memtest.efi", 
triggers the error:

panic: runtime error: slice bounds out of range [298:258]

goroutine 1 [running]:
github.com/foxboron/go-uefi/efi/pecoff.PECOFFChecksum({0xc0002a4000, 0x23400, 0x23401})
	github.com/foxboron/go-uefi@v0.0.0-20211120193624-3d898a764ffd/efi/pecoff/checksum.go:66 +0x69c
github.com/foxboron/sbctl.SignFile({0xc00012c720, 0x24}, {0xc00012c750, 0x24}, {0x7ffe3f476e08, 0x1c}, {0x7ffe3f476e28, 0x14}, {0x0, 0x0})
	github.com/foxboron/sbctl/keys.go:200 +0x3b8
github.com/foxboron/sbctl.Sign({0x7ffe3f476e08?, 0x55c84e7b0625?}, {0x7ffe3f476e28, 0x14}, 0x1)
	github.com/foxboron/sbctl/sbctl.go:138 +0x26c
main.glob..func8(0x55c84eb036c0?, {0xc00007c680?, 0x4?, 0x4?})
	github.com/foxboron/sbctl/cmd/sbctl/sign.go:41 +0x1b5
github.com/spf13/cobra.(*Command).execute(0x55c84eb036c0, {0xc00007c600, 0x4, 0x4})
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x55c84eb02a40)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	github.com/foxboron/sbctl/cmd/sbctl/main.go:84 +0xf2

**Comment by medhefgo** [comment]
memest.efi has a short PE optional header that some tools (and firmware) will choke on: https://github.com/memtest86plus/memtest86plus/issues/202

**Comment by debrouxl** [comment]
Could you test whether the recent integration of https://github.com/memtest86plus/memtest86plus/pull/34 to the main branch of memtest86+ fixed the issue, as expected in https://github.com/memtest86plus/memtest86plus/issues/202 ? Thanks in advance :)

**Comment by WinterStar2** [comment]
I already tried signing the new memtest86+ efi version 6.01 which came out yesterday, but encountered the same error unfortunately.

**Comment by debrouxl** [comment]
Ah, so you're saying that the issue remains present on memtest86+ commit 186ef6e91333badfe315c9b2616991bd238da3f6 ? The Secure Boot support commits were added after the 6.01 tag.

**Comment by WinterStar2** [comment]
Sorry, haven't tried anything with commits after 6.01 yet. I thought this was one of the 6.01 version's improvements. I personally, will wait until an official release containing the Secure Boot support commits is released, however, so my testing will be postponed until such time.

**Comment by WinterStar2** [comment]
OK, just installed the latest 6.10-1 package and was able to successfully sign and boot the .EFI file. Confirmed as working.

**Comment by Foxboron** [comment]
Thanks!
