### ISSUE TITLE
Support UKI files with `kernel-install`

### ISSUE THREAD

**Issue by 05storm26** [Foxboron/sbctl#177]
Currently the `/usr/lib/kernel/install.d/91-sbctl.install` will sign the kernel image of the kernel which is installed using `kernel-install` at the `$ENTRY_DIR_ABS/linux` location. 

Currently when an UKI is installed to the `/<esp>/EFI/Linux/<image>.efi` location the script fails. 

The script should support automatically signing UKI images installed with `kernel-install`

**Comment by 05storm26** [comment]
@Foxboron Should the code sign it before the image is copied to the proper place or after it?

i.e.: for uki layout, should we sign `$KERNEL_INSTALL_STAGING_AREA/uki.efi` or `$KERNEL_INSTALL_BOOT_ROOT/EFI/Linux/$KERNEL_INSTALL_ENTRY_TOKEN-$KERNEL_VERSION*.efi`?

If we decide to sign the image in the staging dir before it is copied into place by [`90-uki-copy.install`](https://github.com/systemd/systemd/pull/25505), then we would need to change `91-sbct.install` to `89-sbctl.install` to make it run before the copying. 

@Foxboron what do you think?

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/commit/1423250cdc3adc28d07f6719231686ffe1b4b4d0
