### ISSUE TITLE
cant activate / enable GPU driver in Windows after creating own keys

### ISSUE THREAD

**Issue by ryanrudolfoba** [Foxboron/sbctl#182]
I've generated keys and enrolled them with the -m option. This seems to work and it shows that microsoft vendor keys has been added to the signature database -

![image](https://user-images.githubusercontent.com/98122529/207613560-6f2442d4-96b6-4ad4-831d-fffc01e88d2e.png)

![image](https://user-images.githubusercontent.com/98122529/207613479-9cf96366-c390-4584-b56f-5936aed47c84.png)

But when I boot to Windows 10 / Windows 11, the GPU driver can't be enabled it complains of key mismatch. I've tried to uninstall / reinstall the GPU driver. It installs fine but in Device Manager it is not able to activate / enable the driver because of key mismatch.

As a workaround I disable driver signing and GPU driver gets activated. Is this expected behavior?

**Comment by Foxboron** [comment]
This is a tool to support self-enrolled keys on Linux. I don't know how this works on Windows.

**Comment by ryanrudolfoba** [comment]
sorry i should have added this to the initial question.

When doing sbctl enroll-keys -m, does it do the below steps automatically -

The [Microsoft Windows Production PCA 2011 certificate](https://www.microsoft.com/pkiops/certs/MicWinProPCA2011_2011-10-19.crt) must be included in the DB variable in order to allow the Windows Operating System to load.

The [Microsoft Corporation UEFI CA 2011 certificate](https://www.microsoft.com/pkiops/certs/MicCorUEFCA2011_2011-06-27.crt) aka the Microsoft 3rd Party UEFI CA certificate should be included in the DB variable in order to use third-party binaries like UEFI drivers, option ROMs, [shim](https://archlinux.org/packages/?name=shim), etc.

The [Microsoft Corporation KEK CA 2011 certificate](https://www.microsoft.com/pkiops/certs/MicCorKEKCA2011_2011-06-24.crt) should be included in the KEK variable, in order to "enable revocation of bad images by updating the DBX and potentially for updating DB to prepare for newer Windows signed images". However, Windows will also boot without the "Microsoft Corporation KEK CA 2011" certificate.

**Comment by Foxboron** [comment]
The KEK CA is currently omitted.

Both the Production PCA and UEFI CA are included.

https://github.com/Foxboron/sbctl/tree/master/certs/microsoft

**Comment by ryanrudolfoba** [comment]
thanks! that may be my issue then! i'll fiddle around.

**Comment by ryanrudolfoba** [comment]
straight from the factory my hardware doesnt have PK KEK DB. and i cant enable secure boot because of that.

i stumbled upon sbctl and i managed to enable secure boot using the self generated keys.

**Comment by Foxboron** [comment]
@sza-1 There is no contradiction. `sbctl` intends to retain the OEM certificates if the users wants that.

**Comment by Foxboron** [comment]
@ryanrudolfoba Feel free to write it down in this issue if you figure it out in the end. I do appreciate learning about quirks even if I can't help solve them :)

**Comment by ryanrudolfoba** [comment]
for sure i'll update this when i get it working.
is there a reason why you didn't include the KEK CA?

**Comment by Foxboron** [comment]
It's only purpose is to accept updates to the `db` and `dbx` which is covered by your self-enrolled key. Since it's not part of any trust chains I didn't come up with a good reason to include it, so I skipped it.

It can be implemented if there is a need though.

**Comment by ryanrudolfoba** [comment]
im trying to add the KEK CA......

the self-generated keys by sbctl are saved in /usr/share/secureboot (PK.key, KEK.key, db,key)
but i also need the corresponding PK.crt, i poked around but i cant seem to find where it is saved?

**Comment by ryanrudolfoba** [comment]
ive added the MS KEK CA but didnt made a difference. when i dual boot to Windows the GPU drivers still doesnt like it when Secure Boot is enabled. something else is at play.

**Comment by vivaldor** [comment]
how do you disable the signature of the gpu driver ?because I found on the internet how to disable signatures in general but it is only valid when secure boot is disabled

**Comment by ryanrudolfoba** [comment]
> how do you disable the signature of the gpu driver ?because I found on the google how to disable signatures in general but it is only valid when secure boot is disabled

Are you referring to this ?
> As a workaround I disable driver signing and GPU driver gets activated

I disable driver signing functionality of Windows.

**Comment by vivaldor** [comment]
yes I am talking about that except that when you deactivate with secure boot activated it does not deactivate anything
