### ISSUE TITLE
fwupd & hp dev one signing error

### ISSUE THREAD

**Issue by pops64** [Foxboron/sbctl#184]
Trying to update the firmware on my laptop. I made sure all keys were singed that were output in the `sbctl verify` command output. All keys were signed then went to restart. The update started but went straight to reboot. I checked fwupd to see the error `authentication signing error`. Is there any debug output you would need? Also on reboot it says the HP's BiosMgmt.efi file is no longer signed even tho I did this before reboot. I changed fwupd config file to not use shim and I tried the `DisableCapsuleUpdateOnDisk=true` found on fwupd git. Not sure what to try next.

I can't disable secure boot I have it on to enable TPM to decrypt the drive. I am on Arch Linux with systemd boot mgr with no fstab or crypttab using systemd auto discovery feature.

This hp efi file did appear after running fwupd for the first time.

Thanks

**Comment by Foxboron** [comment]
Was this issue resolved?

**Comment by pops64** [comment]
No. I just move OS to Pop with out secure. It seems to be a separate EFI OS specifically designed to update the UEFI. Still not sure why secure boot didn't want to launch it even tho it was singed.
