### ISSUE TITLE
Error: prohibited by secure boot priority 

### ISSUE THREAD

**Issue by zeelrupapara** [Foxboron/sbctl#185]
##### Anyone any idea why I get this error 
![image](https://user-images.githubusercontent.com/48467846/209535858-a5b2cd7e-8b5c-4b88-b81d-57058358c6bc.png)

**Comment by Foxboron** [comment]
Grub required all modules requires during boot to be built into the binary and not sideloaded.

See https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#shim_with_key_and_GRUB
