### ISSUE TITLE
Add support for custom OEM keys

### ISSUE THREAD

**Issue by Cornelicorn** [Foxboron/sbctl#190]
This is a feature request to support enrolling custom SecureBoot DB certificates in addition to the current oem certificates given by the enroll options `--microsoft` and `--tpm-eventlog`.
I think this could be implemented by adding a new OEM, which stores it's certificates in a subdirectory of `/usr/share/secureboot/`

My direct usecase would be for building custom kernel modules and signing them, e.g. for DKMS enrolling `/var/lib/dkms/mok.pub` in Debian.

**Comment by Cornelicorn** [comment]
This is somewhat related to https://github.com/Foxboron/sbctl/issues/52, in the case of using DKMS, all modules are automatically signed by a single key, so the enrollment of this key would suffice.

**Comment by Foxboron** [comment]
The issue is that the Debian kernel is patched, or you need a MOK which `sbctl` doesn't support. Having support for custom enrollment of stuff should be done, but it's important to note that this won't necessarily allow signed DKSM modules.

**Comment by Cornelicorn** [comment]
The option to enroll custom keys into the DB would be nice regardless of module-signing.


> but it's important to note that this won't necessarily allow signed DKSM modules

Yes I understand.
For my use case it works if I create an authenticated variable
```
sbsiglist --owner $(</usr/share/secureboot/GUID) --type x509 --output dkms.esl /var/lib/dkms/mok.pub
sign-efi-sig-list -a -g $(</usr/share/secureboot/GUID) -k /usr/share/secureboot/keys/KEK/KEK.key -c /usr/share/secureboot/keys/KEK/KEK.pem db dkms.esl /boot/efi/add_dkms.auth
```
and use this file to enroll it from the Firmware setup utility, but I'm trying to look for a more automatic solution.
