### ISSUE TITLE
/etc/kernel/cmdline does not exist!

### ISSUE THREAD

**Issue by EtereosDawn** [Foxboron/sbctl#197]
i run "sbctl bundle -s -i " but  /etc/kernel/cmdline does not exist!

**Comment by jloeser** [comment]
Existence of this file depends on your distribution, this is not really an issue of `sbctl`.

If you have already booted your productive system (not installer) you could use `/proc/cmdline`:
```
# sbctl bundle -s -c <(cat /proc/cmdline) -f /boot/initrd.img -k /boot/vmlinuz /boot/efi/linux-bundle.efi
```
 
If not, or if you are going to change your cmdline you will need to create a file containing required and desired parameters.

**Comment by Foxboron** [comment]
Please create the file :)
