### ISSUE TITLE
sbctl "failed signing /efi/vmlinuz-linux: /efi/vmlinuz-linux does not exist"

### ISSUE THREAD

**Issue by vandersdg** [Foxboron/sbctl#199]
If i run the command "ls" inside my efi folder, I get the following files: "amd-ucode.img  initrd  initrd-fallback	linux". The vmlinuz-linux really doesn't exists and surprisingly, my system is able to boot just fine without it. However, when the hook tries to sign all files after a kernel update, it returns the error described at the title and it doesn't let the process finish successfully. If anyone can help me with this I would be grateful.

**Comment by Foxboron** [comment]
Which hook? What distribution is this?

**Comment by vandersdg** [comment]
> Which hook? What distribution is this?

I am using dracut on endeavouros.

**Comment by vandersdg** [comment]
After a kernel update to 6.1.12, now "sbctl verify" says that the files of the old kernel doesn't exists. I think it is related with the sbctl saving the old files in a configuration file and not updating it. I feel like if it was a browser I would fix it by wiping the cache and the data and restarting it again.

# sbctl verify
Verifying file database and EFI images in /efi...
(signed files ommited)
‼ /efi/machine-id/6.1.11-hardened1-1-hardened/linux does not exist
‼ /efi/vmlinuz-linux does not exist

**Comment by Foxboron** [comment]
I don't know why you would save the unique path of an old kernel. If you use `kernel-install` then everything should be signed and removed without the need for anything else.

It's unclear to me if this is a bug in the `kernel-install` file, the EndeavourOS `kernel-install` implementation or wrong usage of `sbctl sign -s`.

**Comment by vandersdg** [comment]
> I don't know why you would save the unique path of an old kernel. If you use `kernel-install` then everything should be signed and removed without the need for anything else.
> 
> It's unclear to me if this is a bug in the `kernel-install` file, the EndeavourOS `kernel-install` implementation or wrong usage of `sbctl sign -s`.

Well, the unique paths with the name of the kernels is created by kernel-install (I'm using two AUR packages to do that: "dracut-hook" and "kernel-install-for-dracut"). However, now I managed to temporarily fix the issue by running the command "sbctl remove-file /efi/machine-id/6.1.11-hardened1-1-hardened/linux && sbctl remove-file /efi/vmlinuz-linux". Not sure if in the next kernel update I'll face the same issue again...

**Comment by vandersdg** [comment]
> > I don't know why you would save the unique path of an old kernel. If you use `kernel-install` then everything should be signed and removed without the need for anything else.
> > It's unclear to me if this is a bug in the `kernel-install` file, the EndeavourOS `kernel-install` implementation or wrong usage of `sbctl sign -s`.
> 
> Well, the unique paths with the name of the kernels is created by kernel-install (I'm using two AUR packages to do that: "dracut-hook" and "kernel-install-for-dracut"). However, now I managed to temporarily fix the issue by running the command "sbctl remove-file /efi/machine-id/6.1.11-hardened1-1-hardened/linux && sbctl remove-file /efi/vmlinuz-linux". Not sure if in the next kernel update I'll face the same issue again...

The kernel was now updated and I faced no issue, maybe this was a bug or my fault. I am closing it.
