### ISSUE TITLE
Couldn't sync PK.key: no such file

### ISSUE THREAD

**Issue by willrabbermann** [Foxboron/sbctl#200]
Hello, I used sbctl and it worked very well in the past. 

Recently I cleared my tpm, including my old keys. And maybe accidentally deleted everything in ```rm -f /usr/share/secureboot/keys/*/*```
including my PK.key...

When I clear my tpm from the UEFI menu, it does not reset to the default PK. Ive cleared the tpm from within windows hoping it would give me a microsoft pk, but no. Oh well. I can still boot my computer without secure boot (dell xps 13) but `deployed` secure boot mode only works with windows at the moment. Let me know if I irrecoverably botched my EFI vars.

```
$ sbctl import-keys

$ sbctl create-keys
Created Owner UUID (......)
✓ Secure boot keys has already been created!

$ tree /usr/share/secureboot/keys
/usr/share/secureboot/keys
├── db
├── KEK
└── PK
```

```
$ sbctl status
Installed:	✓ sbctl is installed
Owner GUID:	(......)
Setup Mode:	✗ Enabled
Secure Boot:	✗ Disabled
Vendor Keys:	microsoft
```

```
$ sbctl enroll-keys --microsoft
Enrolling keys to EFI variables...✗
couldn't sync keys: open /usr/share/secureboot/keys/PK/PK.key: no such file or directory
```

```
$ sbctl reset
open /usr/share/secureboot/keys/PK/PK.key: no such file or directory
```

**Comment by Foxboron** [comment]
The TPM has nothing to do with secure boot.

Please reset the Secure Boot setting through the BIOS menu, revert to user mode as previously and run `rm /usr/share/secureboot/` to revert the setup.

**Comment by willrabbermann** [comment]
That worked. Maybe this could be an sbctl command? to `rm -rf /usr/share/secureboot/` and `sbctl create-keys`, called `re-install` with a warning that it toasts your old keys. Or whatever, thank you.

**Comment by Foxboron** [comment]
This is a weird failure mode. I think using `sbctl rotate-keys` might have given you a better solution than manually removing the keys.

**Comment by willrabbermann** [comment]
$(sbctl | grep rotate-keys) = null
I have sbctl 0.9 but 0.10 is on unstable ~amd64 in gentoo repo.
