### ISSUE TITLE
Custom location for keys

### ISSUE THREAD

**Issue by physkets** [Foxboron/sbctl#203]
Separate from the discussion about moving form `/usr/share/` to `/etc` ( #57 ), would it be possible to set a custom location for the keys?

This will be useful for systems configured to use per-home-dir encryption with systemd-homed, which is becoming quite popular. If one of the users is the admin and the keys exist somewhere in their home directory, for eg. `~/.config/secureboot/`, then automatic signing should work fine when they install/update kernels, etc..

Can this already be done?

**Comment by Foxboron** [comment]
I'm not sure if I think `~/.config` is a valid location, however this should be easy to implement if we get the config support landed.

https://github.com/Foxboron/sbctl/issues/6

However this can't be done today. I should try and work on that soon'ish.

**Comment by physkets** [comment]
Yes, that will solve the problem. This issue is then a duplicate.
