### ISSUE TITLE
Problem with Dell Inspiron 14 5425

### ISSUE THREAD

**Issue by rV4nxZ** [Foxboron/sbctl#204]
So it is strange, i followed some issue that has some person with Dell but it was only enrolling keys so i only have signed these files: /boot/EFI/Arch_Linux/grubx64.efi, /EFI/Boot/bootx64.efi, /EFI/Microsoft/Boot/bootmgr.efi, bootmgfw.efi and memtest.efi, setup mode is enabled and secure boot disabled, but when I put the mode in deployed mode, grub days invalid policy or something like that, please help

**Comment by Foxboron** [comment]
That is somewhat expected.

Please read the proper setup instructions for grub.

https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#shim_with_key_and_GRUB

**Comment by rV4nxZ** [comment]
Can you help me?

**Comment by Foxboron** [comment]
Yo, please consult the documentation. This issue tracker isn't really for grub support.
