### ISSUE TITLE
`sbctl verify` returns `failed to find EFI system partition` even though it's there

### ISSUE THREAD

**Issue by moviuro** [Foxboron/sbctl#207]
Hi,

`sbctl verify` returns `failed to find EFI system partition` even though it's there. Unmounting then mounting makes it work. There were no glaring issues with `/efi` (could read, write, no problem).

```
# cat /etc/fstab
UUID=F2D4-5BC4                                  /boot           vfat            rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro                                    0       2
UUID=F2D4-5BC4                                  /efi            vfat            rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro                                    0       2
```

Quick console session:

<details>
  <summary>Console session</summary>

```
% findmnt /boot
TARGET SOURCE         FSTYPE OPTIONS
/boot  /dev/nvme0n1p1 vfat   rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro
% findmnt /efi 
TARGET SOURCE         FSTYPE OPTIONS
/efi   /dev/nvme0n1p1 vfat   rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro
# sbctl verify
failed to find EFI system partition
% tree /efi
/efi
├── EFI
│   ├── Boot
│   │   └── BOOTX64.EFI
│   ├── Linux
│   │   ├── archlinux-linux-clear-fallback.efi
│   │   ├── archlinux-linux-clear.efi
│   │   ├── archlinux-linux-lts-fallback.efi
│   │   └── archlinux-linux-lts.efi
│   ├── memtest86
│   │   ├── Benchmark
│   │   ├── MemTest86-20221014-153419.log
│   │   ├── MemTest86-20230105-174348.log
│   │   ├── MemTest86.log
│   │   ├── blacklist.cfg
│   │   ├── memtestx64.efi
│   │   ├── mt86.png
│   │   └── unifont.bin
│   └── systemd
│       └── systemd-bootx64.efi
├── amd-ucode.img
├── f7522b4f7bc64ecb9c928c6a3f7e481e
├── initramfs-linux-clear-fallback.img
├── initramfs-linux-clear.img
├── initramfs-linux-lts-fallback.img
├── initramfs-linux-lts.img
├── key
├── loader
│   ├── entries
│   │   ├── memtest86-efi.conf
│   │   ├── toxo-clear-efi.conf.disabled
│   │   ├── toxo-clear.conf
│   │   ├── toxo-lts.conf
│   │   └── toxo-lts.conf_20221014T151752Z
│   ├── entries.srel
│   ├── loader.conf
│   └── random-seed
├── vmlinuz-linux-clear
└── vmlinuz-linux-lts
```

</details>

strace: https://gist.githubusercontent.com/moviuro/8e5f2553fca9e2612b11cb7dd5341eef/raw/df8e25b8cc3259c6e87abc3cc2c3c0ed81519c36/strace%2520sbctl%2520verify%2520(failed).txt

<details>
<summary>remount and rerun</summary>

```
# umount /efi          
# mount /efi           # doesn't work with mount -o remount /efi
# sbctl verify
Verifying file database and EFI images in /efi...
✓ /boot/EFI/Linux/archlinux-linux-clear.efi is signed
✓ /boot/EFI/Linux/archlinux-linux-lts.efi is signed
✗ /efi/EFI/Boot/BOOTX64.EFI is not signed
✗ /efi/EFI/Linux/archlinux-linux-clear-fallback.efi is not signed
✗ /efi/EFI/Linux/archlinux-linux-lts-fallback.efi is not signed
✗ /efi/EFI/memtest86/memtestx64.efi is not signed
✗ /efi/EFI/systemd/systemd-bootx64.efi is not signed
✗ /efi/vmlinuz-linux-clear is not signed
✗ /efi/vmlinuz-linux-lts is not signed
```

</details>

strace: https://gist.githubusercontent.com/moviuro/2315b27c313a22d2b41018559482b27e/raw/809d6cb2b5d2de6171910cedc498ec061713ffe6/strace%2520sbctl%2520verify%2520(success).txt

**Comment by Foxboron** [comment]
Whats the output of `lsblk --json --output PARTTYPE,MOUNTPOINT,PTTYPE,FSTYPE` when `sbctl` fails?

And why are you mounting the esp on /boot and /efi?

**Comment by moviuro** [comment]
```json
{
   "blockdevices": [
      {
         "parttype": null,
         "mountpoint": "[SWAP]",
         "pttype": null,
         "fstype": null
      },{
         "parttype": null,
         "mountpoint": "/mnt/bbb76c63-e4ac-4e39-8897-a120c5d30686",
         "pttype": null,
         "fstype": "btrfs"
      },{
         "parttype": null,
         "mountpoint": null,
         "pttype": "gpt",
         "fstype": null
      },{
         "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
         "mountpoint": "/mnt/F2D4-5BC4",
         "pttype": "gpt",
         "fstype": "vfat"
      },{
         "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
         "mountpoint": null,
         "pttype": "gpt",
         "fstype": "crypto_LUKS"
      }
   ]
}
```

I'm mounting on `/boot` & `/efi` because `sbctl` would `fail to find EFI system partition` with only `/boot` mounted when I set it up (which sounds a lot like the same issue we're discussing now).

```
# gdisk -l /dev/nvme0n1
GPT fdisk (gdisk) version 1.0.9.1

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk /dev/nvme0n1: 488378646 sectors, 1.8 TiB
Model: Sabrent Rocket 4.0 2TB                  
Sector size (logical/physical): 4096/4096 bytes
Disk identifier (GUID): ...
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 5
First usable sector is 6, last usable sector is 488378640
Partitions will be aligned on 256-sector boundaries
Total free space is 250 sectors (1000.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1             256          262399   1024.0 MiB  EF00  EFI system partition
   2          262400       488378640   1.8 TiB     8300  Linux filesystem
```

**Comment by Foxboron** [comment]
```
{
         "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
         "mountpoint": "/mnt/F2D4-5BC4",
         "pttype": "gpt",
         "fstype": "vfat"
      }
```

Why is it mounted to `/mnt/F2D4-5BC4`? When `sbctl` tries to find valid mount points it assumes the fstype to be vfat and pttype to be gpt with parttype `c12a7328-f81f-11d2-ba4b-00a0c93ec93b`, on one of three mountpoints: /boot, /efi and /boot/efi.

So this ESP setup is quite weird?

**Comment by moviuro** [comment]
> So this ESP setup is quite weird?

No, I'm just mounting my disks where they make sense. `/mnt/F2D4-5BC4` because it's its UUID, and to `/boot` because, well, it's the boot partition. See also `/mnt/bbb76c63-e4ac-4e39-8897-a120c5d30686` which is also my root partition.

**Comment by Foxboron** [comment]
Why are you doing this?

From what I can tell this is mounted last and confuses `sbctl` as I think `lsblk` only lists the last mountpoint pr partition.

**Comment by moviuro** [comment]
> Why are you doing this?

Because why not? All local mountpoints are available in `/mnt`, makes it easier to travel to the "real" root of e.g. btrfs devices, etc.

`sbctl` should instead try to pull info from `/boot`, `/efi`, `/boot/efi`, check that they are mountpoints; and if they are, that they satisfy the set constraints (vfat, parttype, etc.).

**Comment by moviuro** [comment]
```json
# lsblk --json --output PARTTYPE,MOUNTPOINT,PTTYPE,FSTYPE,MOUNTPOINTS
{
   "blockdevices": [
      {
         "parttype": null,
         "mountpoint": "[SWAP]",
         "pttype": null,
         "fstype": null,
         "mountpoints": [
             "[SWAP]"
         ]
      },{
         "parttype": null,
         "mountpoint": "/mnt/bbb76c63-e4ac-4e39-8897-a120c5d30686",
         "pttype": null,
         "fstype": "btrfs",
         "mountpoints": [
             "/mnt/bbb76c63-e4ac-4e39-8897-a120c5d30686", "/"
         ]
      },{
         "parttype": null,
         "mountpoint": null,
         "pttype": "gpt",
         "fstype": null,
         "mountpoints": [
             null
         ]
      },{
         "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
         "mountpoint": "/mnt/F2D4-5BC4",
         "pttype": "gpt",
         "fstype": "vfat",
         "mountpoints": [
             "/mnt/F2D4-5BC4", "/efi", "/boot"
         ]
      },{
         "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
         "mountpoint": null,
         "pttype": "gpt",
         "fstype": "crypto_LUKS",
         "mountpoints": [
             null
         ]
      }
   ]
}
```

Looks promising!

**Comment by Foxboron** [comment]
Yes, so also check if it's present in `MOUNTPOINTS` then. That should be nice solution.

**Comment by Crysambrosia** [comment]
I have the same issue, however when running `lsblk --json --output PARTTYPE,MOUNTPOINT,PTTYPE,FSTYPE` my partitions show `null` as `pttype` and `fstype` and I have no idea how to fix them :

```json
{
   "blockdevices": [
      {
         "parttype": null,
         "mountpoint": "[SWAP]",
         "pttype": null,
         "fstype": null
      },{
         "parttype": null,
         "mountpoint": "/",
         "pttype": null,
         "fstype": null
      },{
         "parttype": null,
         "mountpoint": "/home",
         "pttype": null,
         "fstype": null
      },{
         "parttype": null,
         "mountpoint": null,
         "pttype": null,
         "fstype": null
      },{
         "parttype": null,
         "mountpoint": "/efi",
         "pttype": null,
         "fstype": null
      },{
         "parttype": null,
         "mountpoint": null,
         "pttype": null,
         "fstype": null
      }
   ]
}
```
Please note that `/efi` is a regular partition, while the others are logical volumes on an encrypted partition. I don't know if that makes a difference.

**Comment by Foxboron** [comment]
If `lsblk` is reporting null I suspect `udev` has some issues. This isn't a `sbctl` issue, strictly speaking. You can set `ESP_PATH` manually.

**Comment by Lazerbeak12345** [comment]
What next steps could be taken by the part of the community that is experiencing this (such as me), to debug this and get the issue fixed (likely upstream in udev or lsblk)? Has it been reported upstream yet?

(yes I'm experiencing the null values, setting the mentioned environment variable silenced the error, and I was able to set up secure boot :tada:)

**Comment by Cornelicorn** [comment]
I think this has nothing to do with udev, it's just that the [partition type](https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs) is not set in the partition table.
The GUID partition type is check in sbctl.go https://github.com/Foxboron/sbctl/blob/d3e9315907de0568f175f1ca9a6c617009a8323d/sbctl.go#L96

So if you're using a GPT disk, vfat on the esp (nothing you can really choose otherwise) and the correct partition type is set, it should work.

If you want to set that partition type GUID, you can use
```
sfdisk --part-type <disk with esp> <partition number of esp> "c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
```
which will change the partition type. Be sure to unmount the ESP before running that command.
After that command, it should also not show `null` anymore in the `lsblk` output

**Comment by Lazerbeak12345** [comment]
I ran `sfdisk --part-type /dev/nvme0n1 1` and the result was the (uppercased) number you specified.

At least in my case, the partition type is correct, and not the problem.

**Comment by Lazerbeak12345** [comment]
Different question: could it be that the code is doing a case-sensitive string comparison when it shouldn't be?

**Comment by tblancher** [comment]
My problem appears to be `lsblk -f` doesn't show any UUIDs, and the JSON output has the null values in its output.  
But I'm in the arch-chroot of a new install.  All the other `sbctl` commands appear to have succeeded, and it's just `sbctl verify` which is failing.  I'm installing a UKI and it's signed (installing the kernel ran the kernel-install hooks, and everything looked successful).  When I exit the arch-chroot, `lsblk -f` shows the UUIDs, but there's not enough space in airootfs to install sbctl and all of its dependencies.

When I originally did this, I had the variable set to `EFI_PATH=/efi`, not `ESP_PATH=/efi`.  Setting the latter allowed `sbctl verify` to work.  I noticed the files installed by systemd-boot aren't yet signed, so I'm going to sign them, but I'm thinking being in the arch-chroot may be a clue to what's going on.

**Comment by Foxboron** [comment]
@tblancher Are you using udev?

**Comment by tblancher** [comment]
> @tblancher Are you using udev?

I believe I am, but I didn't do anything to set it up.  This was in the Arch chroot of a new install, so it's whatever the standard boot of the Arch ISO does automatically.

**Comment by Lazerbeak12345** [comment]
Artix at least (which is based on Arch, if you aren't familiar) uses udev by default. Seeing as moving to udev from something else isn't part of the Arch -> Artix system migration guide, I'd assume that Arch uses udev by default as well.

**Comment by Foxboron** [comment]
See the manpage. 

https://github.com/Foxboron/sbctl/blob/master/docs/sbctl.8.txt#L389

**Comment by neddey** [comment]
even with esp path set in environment variables I still seem to get the `failed to find EFI system partition` error

**Comment by Foxboron** [comment]
Please post complete error messages and the output of `env.

**Comment by neddey** [comment]
```
SHELL=/usr/bin/bash
COLORTERM=truecolor
HYPRLAND_CMD=Hyprland
XDG_BACKEND=wayland
KITTY_PID=4783
XCURSOR_SIZE=24
EDITOR=nano
XDG_SEAT=seat0
PWD=/home/neddey
LOGNAME=neddey
XDG_SESSION_DESKTOP=hyprland
QT_QPA_PLATFORMTHEME=qt6ct
XDG_SESSION_TYPE=wayland
KITTY_PUBLIC_KEY=1:kd}^YQjK@8;Q+B|=V;gM4)xq{XnFCMd+-ihaFM`R
MOTD_SHOWN=pam
HOME=/home/neddey
LANG=C
_JAVA_AWT_WM_NONREPARENTING=1
XDG_CURRENT_DESKTOP=Hyprland
WAYLAND_DISPLAY=wayland-1
KITTY_WINDOW_ID=1
ESP_PATH=/efi
XDG_SESSION_CLASS=user
TERMINFO=/usr/lib/kitty/terminfo
TERM=xterm-kitty
USER=neddey
HYPRLAND_INSTANCE_SIGNATURE=360ede79d124ffdeebbe8401f1ac4bc0dbec2c91_1713174123
VISUAL=nano
DISPLAY=:0
SHLVL=1
MOZ_ENABLE_WAYLAND=1
XDG_VTNR=2
XDG_SESSION_ID=1
LC_CTYPE=C.UTF-8
XDG_RUNTIME_DIR=/run/user/1000
DEBUGINFOD_URLS=https://debuginfod.artixlinux.org
XDG_DATA_DIRS=/home/neddey/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
PATH=/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
MAIL=/var/spool/mail/neddey
KITTY_INSTALLATION_DIR=/usr/lib/kitty
_=/sbin/env
```

**Comment by NyaomiDEV** [comment]
`pttype` is still referenced but it shows up on the physical disk, and it doesn't seem to be propagated to individual partitions.

you can check that with `sudo lsblk --json --output-all` on artix

**Comment by NyaomiDEV** [comment]
oh by the way you can also use
`# lsblk --tree --json --output PARTTYPE,MOUNTPOINT,PTTYPE,FSTYPE`

and it would still be enough

**Comment by Foxboron** [comment]
Please test the proposed fix and give the complete, and unredacted output, of ` lsblk --tree --json --output PARTTYPE,MOUNTPOINT,PTTYPE,FSTYPE,MOUNTPOINTS` if it still fails.


https://github.com/Foxboron/sbctl/pull/358

**Comment by NyaomiDEV** [comment]
@Foxboron it works in my laptop! Thanks a lot

**Comment by Lazerbeak12345** [comment]
Works for me!
