### ISSUE TITLE
Sbctl does not work with read-only /usr

### ISSUE THREAD

**Issue by gdonval** [Foxboron/sbctl#215]
As it is, `sbctl` [uses `/usr` to write state](https://man.archlinux.org/man/community/sbctl/sbctl.8.en). `sbctl import-keys` does support specifying paths but it looks like said keys will just be copied in `/usr/share/secureboot` anyway which is presented as "default" but without documented way of changing it AFAIK.

This would be absolutely fine if **Arch** was signing its own kernels and provided corresponding certificates in `/usr` for registration with `sbctl` or other at install time. 

For *user-generated* data however, `/usr` is not the right place to store said data as this is [intended to be a shareable folder mountable as read-only](https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/usr.html):

>  /usr is shareable, read-only data. That means that /usr should
be shareable between various FHS-compliant hosts and must not be written to.
Any information that is host-specific or varies with time is stored elsewhere.

In modern parlance, `/usr` is package manager's turf.

Admin-alterable `sbctl` config file should be in `/etc` (and user-specific override should be located in `$XDG_CONFIG_HOME`, which defaults to `~/.config`) and `sbctl`-generated config (like saved bundles or to-be-signed artifacts) should be in `/var/lib/sbctl`. Custom keys/certs can be present in `/etc` too or e.g. `/var/lib/sbctl/secureboot`.

Whether you agree or not on the premise of this, allowing user choose where certs/keys are and letting admins set those variables in `/etc/sbctl.conf` sounds like a net win: `sbctl` would become trivially useable on any Linux distribution. As a bonus, if it's implemented in a modular way, it would pave the way to allowing `tpm`-/`fido`-/`luks`-hold keys. A step in the right direction.

**Comment by Foxboron** [comment]
Duplicate issue here https://github.com/Foxboron/sbctl/issues/57 and https://github.com/Foxboron/sbctl/issues/6

> it would pave the way to allowing tpm-/fido-/luks-hold keys

This is something I'm actively working on by learning how the TPM works these days.
