### ISSUE TITLE
clearing keys via sbctl

### ISSUE THREAD

**Issue by ssari-memory** [Foxboron/sbctl#216]
Is there a chance to delete the default keys (PK, KEK, DB) via sbctl? Or is the BIOS/firmware only place to perform this operation? Can such a feature be added to this key manager?

**Comment by Foxboron** [comment]
Currently `sbctl` only allows you to remove the `PK` so you can do key imports/rotations. Why do you need it to clear all the keys?

**Comment by ssari-memory** [comment]
Actually, I don't need to clear all the keys. Just removing the PK is sufficient but when we boot the machine in user mode and sb-disabled, can the sbctl remove the PK, because in the example enrollment cases, it seems like users should clear the keys from the BIOS before enrolling the new ones.

Thanks for the quick response 👍

**Comment by medhefgo** [comment]
The only way to replace or clear the PK at runtime is by enrolling a new one that has been signed by the current PK (obviously not gonna happen for vendor PKs). This should be enforced even if secure boot is disabled as it basically only  disables image authentication.
So everyone has to go through the firmware interface to prove physical presence.

**Comment by ssari-memory** [comment]
Thanks a lot for your responses.
