### ISSUE TITLE
[RFE] Adding a mkinitcpio post generation hook

### ISSUE THREAD

**Issue by neitsab** [Foxboron/sbctl#218]
Hi, I just setup sbctl for the first time and noticed that manual invocation of `mkinitcpio` would not trigger a re-signing by sbctl. My use case is regenerating a UKI after updating the kernel cmdline.

The wiki for mkinitcpio describes a [post generation hook](https://man.archlinux.org/man/mkinitcpio.8#ABOUT_POST_HOOKS) for this use case[[1]](https://wiki.archlinux.org/title/Unified_kernel_image#Signing_the_UKIs_for_Secure_Boot), albeit one using sbsigntools.

Could that be something added to sbctl, like the pacman hook in the contrib/ folder? It's a shame I'm really not proficient at all in shell scripting, otherwise I would have provided one myself, but I'm really not sure what should be tested for etc.

Would you consider adding one to this great utility?
Thanks in any case!

**edit**: I'm on Arch, sbctl version 0.11-1, and other than that everything works fine, UKI signing on kernel install etc. UKI is generated by mkinitcpio and placed into `/boot/efi/EFI/Linux/arch-linux.efi`.

**Comment by neitsab** [comment]
From my test, it seems that the following works:

```sh
cat << EOF > /etc/initcpio/post/kernel-sbctl
#!/usr/bin/env bash

kernel="$1"
[[ -n "$kernel" ]] || exit 0

# use already installed kernel if it exists
[[ ! -f "$KERNELDESTINATION" ]] || kernel="$KERNELDESTINATION"

sbctl sign "$kernel"
EOF
chmod +x /etc/initcpio/post/kernel-sbctl
```

(adapted from [the wiki](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Signing_the_kernel_with_a_mkinitcpio_post_hook))

Or it can be even as simple as:

```sh
cat << EOF > /etc/initcpio/post/uki-sbctl
#!/usr/bin/env bash
sbctl sign-all
EOF
chmod +x /etc/initcpio/post/uki-sbctl
```

if using a UKI with a stable name that has already been added to to sbctl signature database!

**Comment by NekkoDroid** [comment]
you can also do this if you want to explicitly sign the UKIs if they were specified
```sh
#!/usr/bin/env bash
[[ -n "$3" ]] && sbctl sign "$3"
```

**Comment by m00nwtchr** [comment]
Tbh this should probably be the default. Pacman already has a hook which runs mkinitcpio at the right time, and this hook handles both cases.

**Comment by agowa** [comment]
I'm using almost the same one as NekkoDroid.
In addition my version exits when an empty string is provided, I don't recall exactly why I've added that. I just remember that without it something broke...

This is what I wrote for myself:
```
#!/usr/bin/env bash

uki="$3"
[[ -n "$uki" ]] || exit 0

sbctl sign -s "$uki"
```

**Comment by agowa** [comment]
#271 has been merged. Thereby this issue should be partially resolved.
It adds a mkinitcpio post generation hook that runs `sbctl sign-all -g`, the here suggested ones use `sbctl sign -s `

I'll quote from the doc and highlight the important differences between these two approaches.

> sign <FILE>...
>     Signs *an EFI binary* with the created key. The file will be checked for valid signatures to avoid duplicates.
>     -s, --save
>         *Save file to the database.*
> 
> sign-all
>     Signs *all enrolled* EFI binaries.
> 
>     -g, --generate
>         *Generate all bundles* before signing.

**Comment by Bugaddr** [comment]
> I'm using almost the same one as NekkoDroid.
> In addition my version exits when an empty string is provided, I don't recall exactly why I've added that. I just remember that without it something broke...
> 
> This is what I wrote for myself:
> ```
> #!/usr/bin/env bash
> 
> uki="$3"
> [[ -n "$uki" ]] || exit 0
> 
> sbctl sign -s "$uki"
> ```

If I am correct then this will skip signing vmlinuz ?

**Comment by agowa** [comment]
@neitsab can you check if the new hook from #272 also works for you? This Ticket looks kinda resolved to me
(I just come back here as I got another notification from Github about it somehow).

**Comment by neitsab** [comment]
@agowa I followed the recent comments, but as I am AFK for quite some time I cannot test it right away. However, with the initcpio hook added in #271 implementing `sign-all -g`, in principle I don't see why it wouldn't work.

So closing for now as resolved, if someone notices an issue please comment and we'll reopen.
