### ISSUE TITLE
High number and character of prerequisites

### ISSUE THREAD

**Issue by lechner** [Foxboron/sbctl#219]
Hi,

Thanks for your software! I would like to package `sbctl` for GNU Guix. Do you really need to draw on such a large number of prerequisites?

Many of them appear connected to efforts like telemetry or to support proprietary platforms like AppEngine. Thanks!

Kind regards
Felix

**Comment by Foxboron** [comment]
Hi,

>Do you really need to draw on such a large number of prerequisites?

Yes, I'm not re implementing everything to keep the dependency graph small. If the distribution wants to de-vendor Go applications to package each library individually that is on them.

>Many of them appear connected to efforts like telemetry or to support proprietary platforms like AppEngine. Thanks!

That is not true and probably misunderstands the purpose of the dependency.
