### ISSUE TITLE
Segmentation fault when running `sbctl generate-bundles` without `sudo`

### ISSUE THREAD

**Issue by Narcha** [Foxboron/sbctl#224]
What the title says.

![image](https://github.com/Foxboron/sbctl/assets/42248344/95c90c9e-edaa-4eff-9ed1-231bd6285a03)

**Comment by Foxboron** [comment]
Please reopen if this is still an issue

**Comment by Narcha** [comment]
`sbctl generate-bundles` without sudo now fails with a descriptive error message instead :+1:
