### ISSUE TITLE
requires root to run error

### ISSUE THREAD

**Issue by sadanslargehole** [Foxboron/sbctl#240]
Hello! i am getting this error when i try to run 
```bash
sbctl enroll-keys -m
```
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f: permission denied

i am root
i am using an HP Laptop 15-ef2xxx on debian 12 running linux kernel 6.1.0-11-amd64

**Comment by TheHolyTachanka** [comment]
same error for me, on my thinkpad L560

**Comment by sadanslargehole** [comment]
let me know if you find an answer

**Comment by Foxboron** [comment]
Duplicate of https://github.com/Foxboron/sbctl/issues/171
