### ISSUE TITLE
Add support for multiple initramfs images for UKI.

### ISSUE THREAD

**Issue by Kamillaova** [Foxboron/sbctl#243]

**Comment by IPlayZed** [comment]
As per the [UAPI standard](https://uapi-group.org/specifications/specs/unified_kernel_image/) you can not have (and it would not make sense anyway, by definition) more than one initial RAM filesystem.

@Foxboron I think this issue can be closed.

**Comment by Foxboron** [comment]
> As per the [UAPI standard](https://uapi-group.org/specifications/specs/unified_kernel_image/) you can not have (and it would not make sense anyway, by definition) more than one initial RAM filesystem.

This is strictly speaking incorrect as you can always cat together multiple cpio images. They are not going to be more than one initramfs.

> @Foxboron I think this issue can be closed.

The UKI support in `sbctl` is frankly done and I'm not planning on adding more feature. So yes :)
