### ISSUE TITLE
Importing keys fails (replacing sbupdate)

### ISSUE THREAD

**Issue by svenschwermer** [Foxboron/sbctl#245]
Since sbupdate has been deprecated, I'm trying to move over to sbctl. Back when setting up sbupdate, I followed these steps: https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Manual_process

I'm using sbctl v0.11 and this was my initial status:
```
# sbctl status
Installed:	✗ sbctl is not installed
Setup Mode:	✓ Disabled
Secure Boot:	✓ Enabled
Vendor Keys:	none
```
I then attempted to import my existing keys:
```
# sbctl import-keys --db-cert /etc/efi-keys/db.crt --db-key /etc/efi-keys/db.key --kek-cert /etc/efi-keys/KEK.crt --kek-key /etc/efi-keys/KEK.key --pk-cert /etc/efi-keys/PK.crt --pk-key /etc/efi-keys/PK.key
Importing /etc/efi-keys/db.crt...✗
could not move /etc/efi-keys/db.crt: open /usr/share/secureboot/keys/db/db.pem: no such file or directory
```
I don't quite understand the error message. Perhaps, someone could help me understand and overcome it? After running the command above, the status is reported as follows:
```
# sbctl status
Installed:	✓ sbctl is installed
Setup Mode:	✓ Disabled
Secure Boot:	✓ Enabled
Vendor Keys:	none
```

**Comment by Foxboron** [comment]
I suspect something is wrong with the import kode. Try `sudo mkdir -p /usr/share/secureboot/keys/{PK,KEK,db}` and try again
