### ISSUE TITLE
Generated bundles and signed files are not added to database.

### ISSUE THREAD

**Issue by IPlayZed** [Foxboron/sbctl#251]
I generated bundles and signed them (and other files as well), however they are not listed by `list-bundles` or `list-files` and they are neither signed by `sign-all` or generated by `generate-bundles`.

`verify` does list them in the EFI partition, among everything else and when signing them explicitly, the files are signed.

When listing the database via cat, it is an empty file:
```
❯ cat /usr/share/secureboot/files.db
───────┬────────────────────────────────────────────────
       │ File: /usr/share/secureboot/files.db   <EMPTY>
───────┴────────────────────────────────────────────────
```
Same is the case for *bundles.db*.

**Comment by Foxboron** [comment]
You forgot `--save` probably?

**Comment by IPlayZed** [comment]
That must be the case, thank you.
