### ISSUE TITLE
'sudo sbctl sign -s linux-zen.efi' failing

### ISSUE THREAD

**Issue by Luh-code** [Foxboron/sbctl#257]
When running 'sudo sbctl sign -s linux-zen.efi' in the /boot/efi/Linux directory, I get this error:
'/boot/efi/Linux/linux-zen.efi: failed to fetch signatures slice: certificate size exceed the binary file'

What does this error mean, and how can I fix it? 

Help would be very much appreciated!

**Comment by Luh-code** [comment]
Fixed it! To anyone having the same problem: try reinstalling the Kernel. After doing that I could sign it no problem.

**Comment by EvilBoi123** [comment]
i've reinstalled my kernel, but it does not work. Is there any further thing i should do?
