### ISSUE TITLE
sbctl skips signing remaining items if one is not found

### ISSUE THREAD

**Issue by cvlc12** [Foxboron/sbctl#265]
If sbctl fails to find a file on the list of files to sign, then it exits and does not try the remaining files. 
I think it should proceed with attempting to sign the remaining files.

Otherwise the following happens during an update:

```
...
(15/17) Updating the desktop file MIME type cache...
(16/17) Signing EFI binaries...
Generating EFI bundles....
✓ Signed /usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed
failed signing /efi/EFI/Linux/982132008de649089768b8fa1887cbe1-6.1.65-1-lts.efi: /efi/EFI/Linux/982132008de649089768b8fa1887cbe1-6.1.65-1-lts.efi does not exist
erreur : la commande n’a pas pu être exécutée correctement
(17/17) Performing snapper post snapshots for the following configurations...
...
```

```
$ sudo sbctl verify
Verifying file database and EFI images in /efi...
✓ /usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed is signed
‼ /efi/EFI/Linux/982132008de649089768b8fa1887cbe1-6.1.65-1-lts.efi does not exist
✗ /efi/EFI/Linux/arch-linux-lts-fallback.efi is not signed
✗ /efi/EFI/Linux/arch-linux.efi is not signed
✓ /efi/EFI/BOOT/BOOTX64.EFI is signed
✓ /efi/EFI/systemd/systemd-bootx64.efi is signed
```

In this example, the missing file was a test file which had been deleted. However the useful UKIs have not been signed after the update.

**Comment by Foxboron** [comment]
This line can be changed to just emit a warning and not `return`.

https://github.com/Foxboron/sbctl/blob/ff5369185b251c3265312a4c2eb8ed759ef197ad/cmd/sbctl/sign-all.go#L41

**Comment by Bugaddr** [comment]
I think along with this there is a need for an uninstall hook that will remove the files from the file database when the base kernel package is removed after #271 patch to avoid failure while pacman hook will perform sign-all
