### ISSUE TITLE
Mkinitcpio post hook not included in Arch package

### ISSUE THREAD

**Issue by Joseph-DiGiovanni** [Foxboron/sbctl#273]
The initcpio target was removed from the pacman hook but the new mkinitcpio hook meant to replace it wasn't added to the arch package pkgbuild.

**Comment by Taijian** [comment]
Yup, I noticed the same issue...

**Comment by Joseph-DiGiovanni** [comment]
@Foxboron this is a pretty big issue with a simple fix.

**Comment by Joseph-DiGiovanni** [comment]
Fixed as of version 0.13 release 2 https://gitlab.archlinux.org/archlinux/packaging/packages/sbctl/-/commit/5cd5bfc2d64221a0fa347571946899f82ccfea03
