### ISSUE TITLE
Automatic signing mkinitcpio post hook not working in latest archlinux package

### ISSUE THREAD

**Issue by Bugaddr** [Foxboron/sbctl#283]
Hello, in recent update i.e. 0.13 automatic signing hook for mkinitcpio #271 is added but archlinux package dosent have support of that https://archlinux.org/packages/extra/x86_64/sbctl . I think something is need to be done in archlinux package PKGBUILD https://gitlab.archlinux.org/archlinux/packaging/packages/sbctl/-/blob/main/PKGBUILD?ref_type=heads

**Comment by Foxboron** [comment]
It's a packaging issue, not an upstream bug issue.
