### ISSUE TITLE
Implement sbctl debug

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/sbctl#287]
`debug` should be a hidden command for debugging purposes. It should list machine/human readable debugging information from efivarfs to help debugging obscure UEFI firmware issues.

**Comment by RaitoBezarius** [comment]
- A flag or something to dump in a tarball the contents of: `*-8be4df61-93ca-11d2-aa0d-00e098032b8c` from `/sys/firmware/efi/efivars` or by default.
