### ISSUE TITLE
Multiple displays and resolution doesn't work

### ISSUE THREAD

**Issue by erdanilevicius** [Foxboron/sbctl#291]
Hi,

Downloaded experimental branch for ubuntu to sign Pop_OS!  everything went good, but after reboot the the OS only detects 1 out 2 monitors and has locked resolution on the monitor, the resolution is form the second smaller monitor and I'm not able to change it. If I delete all keys everything would go back to normal.

**Comment by Foxboron** [comment]
Please give more details. What commands did you run?

**Comment by erdanilevicius** [comment]
Used commands:
sbctl create-keys
sbctl enroll-keys
sbctl verify to check what needs to be signed
sbctl sign-all(didn't do anything for me)
sbctl sign -s (for everything that was shown in the verify)
reboot.

For windows side everything looked good, but I guess the update breaks some stuff, as I was not able to boot into windows when it updated after that.

**Comment by Foxboron** [comment]
Enroll keys with `--microsoft` to load the OEM certificates.

**Comment by erdanilevicius** [comment]
status before enroll:
`
Installed:	✓ sbctl is installed
Owner GUID:	e807fb22-f9db-4b4c-8441-3ce78c29c792
Setup Mode:	✗ Enabled
Secure Boot:	✗ Disabled
Vendor Keys:	none

`

status after enroll
`
Installed:	✓ sbctl is installed
Owner GUID:	e807fb22-f9db-4b4c-8441-3ce78c29c792
Setup Mode:	✗ Enabled
Secure Boot:	✗ Disabled
Vendor Keys:	microsoft
`
one moment for after reboot

**Comment by erdanilevicius** [comment]
status after reboot and with locked resolution:
`Installed:	✓ sbctl is installed
Owner GUID:	e807fb22-f9db-4b4c-8441-3ce78c29c792
Setup Mode:	✓ Disabled
Secure Boot:	✓ Enabled
Vendor Keys:	microsoft`

**Comment by Foxboron** [comment]
Okay, I have no clue what the issue could be.

**Comment by erdanilevicius** [comment]
Ok then it might be something in the OS itself or something with X11. Will test some things out and update later if I find any solutions.
