### ISSUE TITLE
my Bios gone black

### ISSUE THREAD

**Issue by Octopain** [Foxboron/sbctl#309]
my Bios gone black i can use it as from the memory but it wont show in the screen i can use my operating system when i reboot but i cant go to the bios at all i even did cleared the cmos and removed the battery for a while to reset everything i cant reach to the issue  .

``Filesystem keystore:
  /usr/share/secureboot/keys/db/db.key [3272 bytes]
  /usr/share/secureboot/keys/db/db.pem [1757 bytes]
  /usr/share/secureboot/keys/KEK/KEK.key [3272 bytes]
  /usr/share/secureboot/keys/KEK/KEK.pem [1781 bytes]
  /usr/share/secureboot/keys/PK/PK.pem [1757 bytes]
  /usr/share/secureboot/keys/PK/PK.key [3272 bytes]
Invalid key /usr/share/secureboot/keys/PK/PK.pem
 - unknown cert type
Invalid key /usr/share/secureboot/keys/PK/PK.key
 - unknown cert type
Invalid key /usr/share/secureboot/keys/KEK/KEK.key
 - unknown cert type
Invalid key /usr/share/secureboot/keys/KEK/KEK.pem
 - unknown cert type
Invalid key /usr/share/secureboot/keys/db/db.key
 - unknown cert type
Invalid key /usr/share/secureboot/keys/db/db.pem
 - unknown cert type
firmware keys:
  PK:
    /C=Platform Key/CN=Platform Key
  KEK:
    /C=Key Exchange Key/CN=Key Exchange Key
  db:
    /C=Database Key/CN=Database Key
  dbx:
filesystem keys:
  PK:
  KEK:`
  db:
  dbx:
New keys in filesystem:``

**Comment by Foxboron** [comment]
You are probably running with Option ROM. Unplug the GPU (if you can) and reenroll keys with `--microsoft`. Alternatively you can reset the secure boot state on your system.

**Comment by Octopain** [comment]
Thanks I will try

**Comment by Octopain** [comment]
@Foxboron it worked thank you so much for fast response u are the best

**Comment by Foxboron** [comment]
No worries. Closing this issue.
