### ISSUE TITLE
initcpio hook adds temporary files to list

### ISSUE THREAD

**Issue by bseibold** [Foxboron/sbctl#314]
When installing a custom kernel (UKI) using initcpio, currently a temporary file is added to the sbctl list:

```
# sbctl list-files
/boot/EFI/Linux/arch-linux-fallback.efi
Signed:         ✓ Signed

/boot/EFI/Linux/arch-linux.efi
Signed:         ✓ Signed

/efi/EFI/systemd/systemd-bootx64.efi
Signed:         ✓ Signed

/tmp/kernel-install.staging.EnH7Yj/uki.efi: open /tmp/kernel-install.staging.EnH7Yj/uki.efi: no such file or directory
```

This could be solved be changing `sign -s` to `sign` in the hook.

This is potentially related to #306, however I don't think it's exactly the same issue.

**Comment by Foxboron** [comment]
I suspect having `-s` is an issue.
