### ISSUE TITLE
sbctl sign failing with "binary has no valid signatures"

### ISSUE THREAD

**Issue by safforddr** [Foxboron/sbctl#318]
sbctl has been working fine on Fedora until this week.
Now (since last week's change to the new library) sbctl sign is failing with
the error "binary has no valid signatures", which is apparently coming from the
new signing library.

Tested on Fedora 40 and Rawhide:
steps to reproduce:
    [UEFI in setup mode.]
    sbctl create-keys -d /usr/share/secureboot -e /usr/share/secureboot/keys
    sbctl enroll-keys
    sbctl sign --save /boot/efi/EFI/BOOT/BOOTX64.EFI
        "binary has no valid signatures"

HELP - this is a show stopper.

**Comment by Foxboron** [comment]
Is the file already signed by a key not in your keystore?

**Comment by safforddr** [comment]
All of the efi files are signed by Fedora's keys that are in shim/MOK.
I did just revert to sbctl release .14, and it is working fine.
The problem is only if I clone the current master.

**Comment by Foxboron** [comment]
Pushed a commit I suspect should fix the issue. Please give me a headsup if it still doesn't work.

**Comment by safforddr** [comment]
Yes, that fixed it. THANKS!
