### ISSUE TITLE
mkdir /usr/share/secureboot/keys: read-only file system

### ISSUE THREAD

**Issue by rpolyano** [Foxboron/sbctl#319]
Hello,

I am following the example workflow from the docs. I even have a very similar Asus UEFI.

After Clearing All Keys:

```
# sbctl status
Installed:	✓ sbctl is installed
Setup Mode:	✗ Enabled
Secure Boot:	✗ Disabled
Vendor Keys:	none
```

then

```
# sbctl create-keys -d /home/romanp/.secureboot -e /home/romanp/.secureboot/keys
Created Owner UUID 1dd46e15-6bdb-4a07-987e-e30b0d695038
Creating secure boot keys...✓ 
Secure boot keys created!
```
However `enroll-keys` always defaults to `/usr/share`

I am using blendos which I believe may not allow writing to that directory. 

Is it possible to change which directory sbctl enroll-keys works in?

**Comment by Foxboron** [comment]
Yes, please see https://github.com/Foxboron/sbctl/issues/57#issuecomment-2047853512
