### ISSUE TITLE
Disable landlock required for migration

### ISSUE THREAD

**Issue by alosarjos** [Foxboron/sbctl#333]
Not sure if this is a bug, after updating I was prompted to run a `sbctl setup --migration` but it failed until I used the `--disable-landlock` feature. Not sure if this is expected behavior.

It says it needs root permission but I'm already as root

![imagen](https://github.com/user-attachments/assets/48fa0306-7c5d-4355-a869-1ff54ed73a81)

**Comment by Foxboron** [comment]
lol, ofc i forgot to test that.

**Comment by Foxboron** [comment]
Pushed a patch, but probably better to add in my release notes that `--disable-landlock` should be used with `sbctl migrate`.

**Comment by alosarjos** [comment]
Do I need to redo de migration or something once the fix is published?

**Comment by Foxboron** [comment]
No, it should be fine when you ran it with `--disable-landlock`.

**Comment by alosarjos** [comment]
Since the migration command is advised during signing whith older config, you may want to put the --disable-landlock on the prompted command?

**Comment by Foxboron** [comment]
No, it should be fixed with the next release.

**Comment by Foxboron** [comment]
Because of an issue where `files.json` gets overwritten by `bundles.db` it's better to skip `0.15` and go for `0.15.1` which fixes both these issues.

https://github.com/Foxboron/sbctl/issues/334

**Comment by alosarjos** [comment]
> Because of an issue where `files.json` gets overwritten by `bundles.db` it's better to skip `0.15` and go for `0.15.1` which fixes both these issues.
> 
> #334

Any manual thing/task need to be done if I already migrated on 0.15?

**Comment by Foxboron** [comment]
> Any manual thing/task need to be done if I already migrated on 0.15?

If you still have your files database you should be fine.

**Comment by alosarjos** [comment]
> > Any manual thing/task need to be done if I already migrated on 0.15?
> 
> If you still have your files database you should be fine.

The files.json is empty and I guess that lost forever? I need to rerun the sign -s for every file I sued to?

**Comment by Foxboron** [comment]
> The files.json is empty and I guess that lost forever? I need to rerun the sign -s for every file I sued to?

Yep, sadly.

**Comment by alosarjos** [comment]
Just checking the release notes, since I guess lots of people will see this, on `Major changes` for 0.15.0 it says:

```
Please run sbctl migrate --disable-landlock
```

But that command does not exists, so either it's a bug on the code or the command to run should be:

`sbctl setup --migrate --disable-landlock`

**Comment by Foxboron** [comment]
Fixed! Thanks :)
