### ISSUE TITLE
`sbctl setup --migrate` results in empty file database

### ISSUE THREAD

**Issue by FreezyLemon** [Foxboron/sbctl#334]
I just updated to 0.15 and after running

```sh
sudo sbctl setup --migrate --disable-landlock
```

the newly created `/usr/lib/sbctl/files.json` is empty (0 bytes), even though `/usr/share/secureboot/files.db` contained files that I saved via `sbctl sign -s <file>`.

```sh
$ ls -l /var/lib/sbctl
total 4

-rw-r--r-- 1 root root    0 Jul 31 14:02 files.json
-rw-r--r-- 1 root root   36 Jul 31 14:02 GUID
drwxr-xr-x 1 root root   14 Jul 31 14:02 keys

$ cat /var/lib/sbctl/files.json


```

```sh
$ ls -l ~/secureboot-backup
total 8
-rw-r--r-- 1 root root    0 Jul 31 14:01 bundles.db
-rw-r--r-- 1 root root  463 Jul 31 14:01 files.db
-rw-r--r-- 1 root root   36 Jul 31 14:01 GUID
drwxr-xr-x 1 root root   14 Jul 31 14:01 keys

$ cat ~/secureboot-backup/files.db
{
  "/efi/EFI/Linux/Arch.efi": {
    # ...
  },
  # ...
}
```

`sbctl list-files` also does not list any saved files anymore.

**Comment by Foxboron** [comment]
Sorry, fixed with https://github.com/Foxboron/sbctl/commit/80c451c8dea2075e0b7bd04055e271fe88b1f12a and did a new release with `0.15.1`.

Moving your backup `files.db` to `/var/lib/sbctl/files.json` should fix this.

**Comment by FreezyLemon** [comment]
Alright, thanks for the quick response.
