### ISSUE TITLE
sbctl requires root to run: open /usr/share: permission denied

### ISSUE THREAD

**Issue by edwloef** [Foxboron/sbctl#336]
Output when migrating the config:

```
❱ sudo sbctl setup --migrate
old configuration detected. Please use `sbctl setup --migrate`
Moving files...✓ 
sbctl requires root to run: open /usr/share: permission denied
```

this also occurs when running in a root shell instead of with sudo.

**Comment by Foxboron** [comment]
Hrm, weird. I don't know why it would try to open `/usr/share`? Is `/usr/share/secureboot` removed?

**Comment by edwloef** [comment]
No, that folder still exists.

**Comment by oliverhaagh** [comment]
I am also getting the same error with `/usr/share/secureboot` still existing.

**Comment by Kaspian24** [comment]
Sorry if that's not related but I'm getting similar error with create-keys:

sbctl create-keys
sbctl requires root to run: mkdir /var/lib/sbctl: permission denied

Both with sudo or when running in a root shell.

**Comment by ptr1337** [comment]
0.15.2 still has the issue:
```
❯ pacman -Qs sbctl
local/sbctl 0.15.2-1
    Secure Boot key manager

❯ sudo sbctl setup --migrate --disable-landlock
old configuration detected. Please use `sbctl setup --migrate`
/var/lib/sbctl already exists!
```

Same with 0.15.1

**Comment by Foxboron** [comment]
Man, I'm bad at this software thing.

**Comment by Foxboron** [comment]
Okay, so if you see "sbctl requires root to run: open /usr/share: permission denied" during `sbctl setup --migrate` you have migrated all the files to `/var/lib/sbctl`, however `sbctl` could not remove `/usr/share/secureboot` because of landlock.

So `rm -rf /usr/share/secureboot` should be fine.

**Comment by Kaspian24** [comment]
As for sbctl create-keys, it run fine with --disable-landlock.

**Comment by Foxboron** [comment]
This fixes the `create-keys` issue https://github.com/Foxboron/sbctl/commit/61f918052d1c22bf610ffdae033470f390015fef

I'll hold off on a little bit with a new release to see if there are more issues that come up.

**Comment by Foxboron** [comment]
I've broken my personal setup 3 times to try and test this properly. So `0.15.3` should have fixed all of the issues, I hop.

https://github.com/Foxboron/sbctl/releases/tag/0.15.3
