### ISSUE TITLE
sbctl --migrate still saying "old configuration detected"

### ISSUE THREAD

**Issue by ablomm** [Foxboron/sbctl#338]
![image](https://github.com/user-attachments/assets/03dd6bd6-4348-4457-85b3-d5e054a8d46d)

Is this an issue? Was the migration successful? I can't tell.
Running with sudo still complained about not running with root. I don't quite understand.

**Comment by Foxboron** [comment]
You can delete `/usr/share/secureboot` after validating that everything was moved over, it should work fine.

See https://github.com/Foxboron/sbctl/issues/337

**Comment by ablomm** [comment]
> You can delete `/usr/share/secureboot` after validating that everything was moved over, it should work fine.
> 
> See #337

Done, and everything is working fine, thanks for the quick reply!

**Comment by Foxboron** [comment]
No worries! I'll do a new release with the fixes soon :)
