### ISSUE TITLE
Issue with sbctl sign-all -g bundle generation

### ISSUE THREAD

**Issue by hypernormalisation** [Foxboron/sbctl#345]
Hi, I've been having a minor issue on Arch Linux since the most recent update.
Immediately after running mkinitcpio, `sbctl sign-all -g` fails to generate bundles with 

```
$ sudo sbctl sign-all -g
Generating EFI bundles....
failed creating bundle /efi/main.efi: open /usr/lib/systemd/boot/efi/linuxx64.efi.stub: permission denied
File has already been signed /boot/vmlinuz-linux
File has already been signed /efi/main.efi
```

The file `/usr/lib/systemd/boot/efi/linuxx64.efi.stub` has the usual permissions and ownership.

```
$ ls /efi/main.efi -l
-rwxr-xr-x 1 root root 32660624 Aug  1 20:24 /efi/main.efi
$ sudo sbctl list-bundles
/efi/main.efi: open /efi/main.efi: permission denied
```

This is not an issue if I manually run the bundle generation beforehand instead of passing the -g flag to `sign-all`:

```
$ sudo sbctl generate-bundles
Generating EFI bundles....
Wrote EFI bundle /efi/main.efi
$ sudo sbctl sign-all
File has already been signed /boot/vmlinuz-linux
✓ Signed /efi/main.efi
$ ls /efi/main.efi -l
-rwxr-xr-x 1 root root 32660624 Aug  1 20:32 /efi/main.efi
```

Any idea what's causing this issue? It's easy to workaround but given it broke my pacman upgrade hook it'd be nice to understand why this happened. journalctl has nothing relevant.

**Comment by Foxboron** [comment]
Use `--disable-landlock` and/or set `landlock: false` in `/etc/sbctl/sbctl.conf` as a temporary workaround.

**Comment by ooonea** [comment]
With version 0.15.3-1 still this error.

**Comment by Foxboron** [comment]
It will be fixed with https://github.com/Foxboron/sbctl/pull/344

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/releases/tag/0.15.4
