### ISSUE TITLE
sbctl messed up after running "sbctl setup --migrate"

### ISSUE THREAD

**Issue by EricLin0509** [Foxboron/sbctl#355]
I previously installed sbctl and setup the secure boot, after upgrade to version 0.15, it showed me to run "sbctl setup --migrate", so I ran "sbctl setup --migrate --disable-landlock". but it stiil showed me the same message when signing the files. I found the keys were still existed in /usr/share/secureboot/keys (the keys can also be found in /var/lib/sbctl/keys), so I deleted /usr/share/secureboot/keys/ directory; but sbctl can't work after doing this, it said "sbctl is not installed". I ran "sbctl setup --migrate --disable-landlock" again, but it showed sbctl has already migrated. It worked again when I copied files back to /usr/share/secureboot/keys/. And the keys stored in /usr/share/secureboot/keys/ won't be update if I regen the keys.

**Comment by Foxboron** [comment]
Which version are you using? `0.15` or `0.15.4`?

>  deleted /usr/share/secureboot/keys/ directory

If somthing breaks during migration just move the files from this directory and `rm -rf /usr/shar/secureboot`. `sbctl` uses the folder itself to figure out if you have migrated or not.

**Comment by EricLin0509** [comment]
I tried your solution and it works! Thank you so much.
