### ISSUE TITLE
Already signed file doesn't appear in database, can't add it either

### ISSUE THREAD

**Issue by Syndace** [Foxboron/sbctl#359]
I installed a new kernel and apparently due to some automated hook during installation, the vmlinuz file is signed but not in the database. `sbctl list-files` does not list the vmlinuz file and running `sbctl sign -s /boot/vmlinuz` tells me that the file is already signed but doesn't add it to the database either.

Suggestion: make `sbctl sign -s` add files to the database even if they are already signed.

Thanks for this amazing tool <3

**Comment by Foxboron** [comment]
Please test this change https://github.com/Foxboron/sbctl/pull/360

**Comment by Syndace** [comment]
That branch fails to build for me, the full output of `make` is:

```
a2x --no-xmllint --asciidoc-opts="-f docs/asciidoc.conf" -d manpage -f manpage -D docs docs/sbctl.8.txt
a2x --no-xmllint --asciidoc-opts="-f docs/asciidoc.conf" -d manpage -f manpage -D docs docs/sbctl.conf.5.txt
go build -ldflags="-X github.com/foxboron/sbctl.Version=0.15.4.4.gfe847c1" -o sbctl ./cmd/sbctl
# github.com/foxboron/sbctl
./keys.go:104:28: cannot use inputBinary (variable of type *authenticode.PECOFFBinary) as io.ReaderAt value in argument to kh.SignFile: *authenticode.PECOFFBinary does not implement io.ReaderAt (missing method ReadAt)
make: *** [Makefile:28: sbctl] Error 1
```

`go version go1.22.6 linux/amd64`

The master branch builds fine.

**Comment by Foxboron** [comment]
Woops, sorry. Fixed :)

**Comment by Syndace** [comment]
Thanks, works now! The file is added to the database :)
