### ISSUE TITLE
failed parsing pkcs7 signature from binary

### ISSUE THREAD

**Issue by marmitar** [Foxboron/sbctl#373]
Was just testing Grml for recovery (via [grml-systemd-boot](https://aur.archlinux.org/packages/grml-systemd-boot/)) and verification step is not working nicely. It just outputs the following error:

```fish
> sudo sbctl verify /efi/grml/vmlinuz
failed parsing pkcs7 signature from binary: incorrect, expected 1.3.6.1.4.1.311.2.1.4, got 1.3.6.1.4.1.311.2.1.21
```

This does not show up for the first `sign`, only when verifying the image after signed. The image is still bootable, though, so nothing critical, I guess. This error does not affect other images nor executables in ESP.

**Comment by Foxboron** [comment]
This was fixed with [0.15.4](https://github.com/Foxboron/sbctl/releases/tag/0.15.4).

https://github.com/Foxboron/go-uefi/commit/e2076f0e58ca8de9e6e55f4662432700d26fe5c0

**Comment by TiagodePAlves** [comment]
Sorry, I forgot to add my system info, but I'm already on latest version here: 

```fish
> pacman -Qi sbctl
Name            : sbctl
Version         : 0.15.4-1
# ...
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : qua 07 ago 2024 09:33:09
Install Date    : sex 09 ago 2024 02:02:51
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

So, I was already on latest version here, but I reinstalled `sbctl` and `grml-sytemd-boot` and rebooted just to ensure everything is up-to-date. The error message is still there:

```fish
> sudo sbctl verify 
Verifying file database and EFI images in /efi...
✓ /efi/EFI/tools/poweroff.efi is signed
✓ /efi/EFI/tools/reboot.efi is signed
✓ /efi/EFI/Linux/arch-linux-fallback.efi is signed
✓ /efi/EFI/Linux/arch-linux.efi is signed
✓ /efi/EFI/memtest86/memtestx64.efi is signed
✓ /efi/EFI/systemd/systemd-bootx64.efi is signed
✓ /efi/shellx64.efi is signed
failed parsing pkcs7 signature from binary: incorrect, expected 1.3.6.1.4.1.311.2.1.4, got 1.3.6.1.4.1.311.2.1.21
```

One thing to note, I don't have Microsoft keys enrolled:

```fish
> sbctl status
Installed:	✓ sbctl is installed
Setup Mode:	✓ Disabled
Secure Boot:	✓ Enabled
Vendor Keys:	tpm-eventlog
```

**Comment by Foxboron** [comment]
Please upload `/efi/grml/vmlinuz` somewhere so I can look at it.

**Comment by TiagodePAlves** [comment]
Ok, I've uploaded to a [MEGA folder](https://mega.nz/folder/t6FiwQiD#hpvmOzaa-764b8RGK5LWCw).

`vmlinuz` is the same from `grml64-small_2024.02.iso`, and `vmlinuz-signed` is the one signed with my keys.

**Comment by Foxboron** [comment]
okay, lol.

The issue *is* fixed. `sbctl` just doesn't pull the last commit from `go-uefi`.

I'll fix this at some point in the next couple of days.

**Comment by TiagodePAlves** [comment]
Oh, nice! Thanks for finding this so fast.

**Comment by pkern** [comment]
@Foxboron, thanks for sbctl! Could go.mod be updated to include the fix? It looks like this happens with standard Debian kernels from testing/unstable.

**Comment by Foxboron** [comment]
@pkern yes. I intend to do a release within a few days.

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/commit/6855f246e02ca80019e70bfb9db28af91788ee7e
