### ISSUE TITLE
Issues with fwupd-efi and linux 6.11

### ISSUE THREAD

**Issue by zaolin** [Foxboron/sbctl#379]
@Foxboron Did you already experience the following issues?

fwupd-efi v1.6
failed signing /boot/EFI/Gentoo/fwupdx64.efi: incorrect digest

kernel 6.11
Nothing boots up, I don't get any output even with early kernel console..

**Comment by Foxboron** [comment]
I haven't. Please upload the affected file. Unsure why 6.11 would fail to boot?

**Comment by zaolin** [comment]
At least it hangs, I am not sure whats going on there. Normally after systemd-stub load I would see any type of output. I will try to investigate in a VM. Maybe it's an issue on my side, who knows what the AMD folks patched again

**Comment by zaolin** [comment]
Forget about the fwupd-efi, seems like binary got corruption. However that happened

**Comment by zaolin** [comment]
It's the 10 firmware blobs you have to load
