### ISSUE TITLE
Support for atomic distros

### ISSUE THREAD

**Issue by RodrigoPrestes** [Foxboron/sbctl#380]
I've been trying to install sbctl on Fedora Silverblue, but it errors out due to the read-only file system.

I managed to add the copr repo by creating a file on `/etc/yum.repos.d/sbctl.repo` and then running `sudo rpm-ostree install sbctl`.

Here's the error when trying to install:
`error: Executing %transfiletriggerin for sbctl: bwrap(/bin/sh)`
and it tells me to run `journalctl -t 'rpm-ostree(sbctl.transfiletriggerin)'` for more information.

Here's the output:
```
out 02 23:24:13 fedora rpm-ostree(sbctl.transfiletriggerin)[4452]: Generating EFI bundles....
out 02 23:24:13 fedora rpm-ostree(sbctl.transfiletriggerin)[4452]: mkdir /var/lib/sbctl: read-only file system
```

Is there instructions or planned support for these kinds of distros?

**Comment by Foxboron** [comment]
I don't run Fedora Silverblue and similar distros. If you can tell me what is needed to support them I'll write the code to support it at some point.

**Comment by RodrigoPrestes** [comment]
Not really sure what's going on...
As per [documentation](https://docs.fedoraproject.org/en-US/fedora-silverblue/technical-information/#filesystem-layout) `/var` should be writable, and it actually is.
I can mkdir no problem but for some reason rpm-ostree can't write there even running as root.

**Comment by Foxboron** [comment]
I don't know how ostree works. It sounds like some form of packaging issue?

**Comment by pm4rcin** [comment]
@RodrigoPrestes FYI the issue was resolved in copr repo. https://github.com/chenxiaolong/fedora-packages/issues/14

**Comment by Foxboron** [comment]
Cool, thanks! I'll close this issue then :)
