### ISSUE TITLE
Is the FQ0001 quirk warning still up-to-date?

### ISSUE THREAD

**Issue by matteodev8** [Foxboron/sbctl#381]
The warning on MSI mainboards

```
Firmware:	‼ Your firmware has known quirks
		- FQ0001: Defaults to executing on Secure Boot policy violation (CRITICAL)
		  https://github.com/Foxboron/sbctl/wiki/FQ0001
```

is still appearing. Even after a few firmware updates, latest versions, etc... . I don't have the option for the individual execution policies. And I can confirm that secure boot works as intended (not loading the NVIDIA driver without the signature being installed). That's why I am doubting its usefulness today given that it was last updated a year ago to the quirk file. (Using MSI X670E Carbon WiFi)

**Comment by Foxboron** [comment]
Feel free to include it into this array.

https://github.com/Foxboron/sbctl/blob/master/quirks/fq0001.go#L16

**Comment by dawidpotocki** [comment]
I am confused by this issue.

> I don't have the option for the individual execution policies

The newer firmware don't have that, but they still have the "Secure Boot Preset", which changes the execution policies.

> not loading the NVIDIA driver without the signature being installed

I could be wrong on this, but from my understanding it is what the kernel would do itself based on the Secure Boot setting and not something the firmware would have any effect on.

Please try booting without sbctl signing the kernel/UKI and bootloader or try booting some other OS known to not have Secure Boot support.

The PR disables the quirk for the 1.K0 firmware (https://download.msi.com/bos_exe/mb/7D70v1K.zip) but I checked the IFR and I can see the toggle so I fail to see how this firmware would not be affected.

```
EqIdVal QuestionId: 0x28F6, Value: 0x0
OneOf Prompt: "Secure Boot Preset", Help: "Set Hardware/OS Compatibility for some non-UEFI or non-compliant Hardware/OS with optimized functions, or to set Maximum Security for full validation of all components installed.", QuestionFlags: 0x10, QuestionId: 0xF9, VarStoreId: 0xF, VarOffset: 0x4, Flags: 0x10, Size: 8, Min: 0x0, Max: 0x5, Step: 0x0
	Default DefaultId: 0x0 Value: 0
	OneOfOption Option: "Hardware/OS Compatibility" Value: 0, MfgDefault
	OneOfOption Option: "Maximum Security" Value: 5
End
```
