### ISSUE TITLE
"import-keys" fails with RSA key from OpenSSL

### ISSUE THREAD

**Issue by schmidicom** [Foxboron/sbctl#386]
When I try to import a certificate and the corresponding RSA key that was created using XCA (a frontend to OpenSSL) or was once in an archive managed by XCA, it fails with the following error message.
```
# sbctl import-keys --db-cert ./Database_Key.crt --db-key ./db.pem
invalid private key file
```
In this example, I tried it with the certificate created by sbctl itself. Before attempting to import it again with sbctl, the certificate was imported once into XCA and then exported again as PEM.
Does sbctl need a special format for the private key or is this a bug in sbctl?

Here are the links to the certificate, once before importing into XCA and once after: [Database Key](https://drive.google.com/drive/folders/1oSzx8sU3CRI7CyNMEv0yR1yXB6V6Tr8y?usp=sharing)
I no longer use this certificate and can be used for testing.

Here is the link to the software used: [XCA](https://github.com/chris2511/xca)

**Comment by Foxboron** [comment]
It should be the other way around. `Database_Key.crt` is the `--db-key` argument, and `db.pem` is the `--db-cert` argument.

**Comment by schmidicom** [comment]
I've now tried it again and made sure that there is no mix-up between the certificate and the private key. However, the result is still the same.
```
# file db/before_xca/* db/after_xca/*
db/before_xca/db.key: OpenSSH private key (no password)
db/before_xca/db.pem: PEM certificate
db/after_xca/db.key:  PEM RSA private key
db/after_xca/db.pem:  PEM certificate
```
```
# sbctl import-keys --db-cert db/after_xca/db.pem --db-key db/after_xca/db.key 
invalid private key file
```

**Comment by Foxboron** [comment]
Okay, so the XCA keys are RSA PKCS1 keys, while `sbctl` (and by extension `go-uefi`) only supports PKCS8 keys. I don't really consider this a bug and I'm not sure how you would get XCA to output the correct format.

**Comment by schmidicom** [comment]
I've tried it again now (in XCA you can select different formats when exporting) and with a private key in PKCS8 format the import works. Thank you.

It might be a good idea to add to the manpage that the private key must be in PKCS8 format.
