### ISSUE TITLE
Landlock prevents the use of --export in enroll-keys

### ISSUE THREAD

**Issue by ZLima12** [Foxboron/sbctl#387]
Similar to #348 , attempting to run `sbctl enroll-keys --export` since c9d2539 results in a "permission denied" error when not using `--disable-landlock`. I'm not sure if unrestricting the current directory (which may be anywhere) is something that would be desired, so I decided not to make a PR.

**Comment by Foxboron** [comment]
> I'm not sure if unrestricting the current directory (which may be anywhere) is something that would be desired, so I decided not to make a PR.

The current directory needs to be added with `RWDirs`, so feel free to write a patch :)
