### ISSUE TITLE
Using /proc/cmdline may include unnecessary initrd

### ISSUE THREAD

**Issue by physkets** [Foxboron/sbctl#39]
The contents of `/proc/cmdline` at some boot might include the microcode and initramfs supplied as arguments to `initrd`. This is not required any more when creating a bundle because both of those are dealt-with separately.

So should any `initrd` components be trimmed before inclusion?

**Comment by Foxboron** [comment]
`/proc/cmdline` is only a "sane" default. Users are left up to their own device to ensure there isn't uneeded stuff there. I'm unsure if trimming it without any insight is a good idea.

**Comment by chrishoage** [comment]
Is there a "standard" place to put the user-modified `cmdline`? 

I've found how to pass a custom `cmdline` and `os-release` but I've just thrown it in an arbitrary place. 

Has it been considered to have a configuration directory and file for sbctl such that these files would not show up in `lostfiles` and would be controlled by pacman? 

e.g. something like `/etc/sbctl/cmdline` and `/etc/sbctl/os-release`? 

That's fine if it's not in scope, just wasn't sure where the "proper" place to put these overrides were.

**Comment by Foxboron** [comment]
That's a great point actually! I think it ties into #6 for the sake of having configuration setup and more flexibility for the settings.

I'm not sure if any of that solves the `lostfiles` problem though. They are probably not going to be default provided as they are unique for each installation. But I haven't really planned this far yet.

**Comment by chrishoage** [comment]
> They are probably not going to be default provided as they are unique for each installation. But I haven't really planned this far yet.

That makes sense, and is honestly not the end of the world if they appear in lostfiles. 

In any case, something to consider is an empty config file, with example config values commented out. These options override defaults from `cmdline` and `os-release`, along with the default location for the keys. 

This way there is a tracked config file that could be included with the sbctl package. The `pacnew` it creates could serve as a way to inform users of new or changed configuration file. 

Just a thought!

Thanks for this wonderful tool. Made setting up secure boot incredibly painless :slightly_smiling_face:

**Comment by gdamjan** [comment]
the "standard" place for cmdline is `/etc/kernel/cmdline` I guess 

https://www.freedesktop.org/software/systemd/man/kernel-install.html

**Comment by Foxboron** [comment]
Ah yes, reading `/etc/kernel/cmdline` and fallback to `/proc/cmdline` would make a lot of sense. Thank you!
