### ISSUE TITLE
systemd-boot binary should get signed

### ISSUE THREAD

**Issue by erebion** [Foxboron/sbctl#395]
Hey there,

I just installed updates, the systemd-boot binary got replaced and I could no longer boot after rebooting.

In this case I knew that this was because the update just replaced the binary, but for people that left their laptop unsupervised after updating and before rebooting, there would be no way of knowing whether tamper had occured or the systemd-boot binary had just been updated.

In my case, I had to sign `/boot/efi/EFI/systemd/systemd-bootx64.efi` manually.

Instead, `sbctl` should provide some sort of hook that automatically signs the binary when it gets updated, so that the system can still boot without the user having to remember to check for an updated binary before rebooting and to also sign it. :D  

Thanks for this neat tool! :-)

**Comment by Foxboron** [comment]
This is a packaging thing. `sbctl` provides hooks for kernel-install and alpm. If things here is not working as expected that is a downstream distro issue and not something `sbctl` can solve.

> Thanks for this neat tool! :-)

Thanks!

**Comment by erebion** [comment]
>downstream distro issue

Oh, thought it might be. Thanks / Takk for oppklaringen!

Good occasion to mention that the Debian package, which is done, is in need of a maintainer, in case anyone here is looking for a way to contribute to its packaging over on the Debian side. ;-)

https://salsa.debian.org/go-team/packages/sbctl

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030845

**Comment by Foxboron** [comment]
See https://github.com/Foxboron/sbctl/discussions/351 :)
