### ISSUE TITLE
sbctl verify does not output json

### ISSUE THREAD

**Issue by cybik** [Foxboron/sbctl#401]
When running `sbctl verify <FILE>` without arguments, it verifies that a file is signed (or not).

`sbctl verify` is supposed to have a json argument, but using that argument makes sbctl output nothing when running verify against a file, or even at all.

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/commit/cd6dd1c6a02f5b4b3b93669e78671b656ddcfe67
