### ISSUE TITLE
sbctl `enroll-keys`: `couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/PK-8be4df6...: permission denied`

### ISSUE THREAD

**Issue by kmille** [Foxboron/sbctl#406]
I'm using Virtualbox.
```
[root@encbox user]# sbctl status
Installed:      ✓ sbctl is installed
Owner GUID:     b4211084-fff3-4d13-bb98-5379bb14831b
Setup Mode:     ✗ Enabled
Secure Boot:    ✗ Disabled
Vendor Keys:    none
[root@encbox user]# sbctl enroll-keys 
Enrolling keys to EFI variables...✗ 
sbctl requires root to run: couldn't sync keys: couldn't write efi variable: write /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c: permission denied
[root@encbox user]# 
```
![2024-12-16-230841_screenshot](https://github.com/user-attachments/assets/f0b8de02-4f70-412d-83a5-3626c2d08bca)
![2024-12-16-230850_screenshot](https://github.com/user-attachments/assets/ca604a05-77bd-4489-a67f-38cf86b5e2c0)

There is only "Standard Mode" and "Custom Mode"

It seems like I have to add the certs/keys manually. Any experience with that? Thanks for the support!

**Comment by Foxboron** [comment]
I don't know virtualbox so please refer to their documentation.
