### ISSUE TITLE
Missing `/sys/firmware/efi/efivars/SetupMode-8be4df61-93ca-11d2-aa0d-00e098032b8c` EFI variable file

### ISSUE THREAD

**Issue by pjungkamp** [Foxboron/sbctl#407]
I'm trying to enroll secureboot keys into my Framework Laptop 13 Core Ultra 1 Series (latest firmware, kernel 6.12.5) but e.g. `sbctl status` shows `system is not booted with UEFI`. Is this a bug in the Firmware or in `sbctl`?

**Comment by Foxboron** [comment]
Are you booting UEFI or legacy?

**Comment by Foxboron** [comment]
That looks like broken firmware to me. Please report it to the Framework people.

**Comment by pjungkamp** [comment]
Just found it on the framework forums... my bad.
https://community.frame.work/t/putting-secureboot-into-setup-mode-breaks-several-efi-tools/62033

**Comment by Foxboron** [comment]
Cool. Thanks for confirming :) Closing this issue.

**Comment by pjungkamp** [comment]
For future reference, look here: https://community.frame.work/t/cant-enable-secure-boot-setup-mode/57683/5
