### ISSUE TITLE
Improve GetESP()

### ISSUE THREAD

**Issue by gdamjan** [Foxboron/sbctl#44]
`GetESP()` in `sbctl.go` assumes that there is only one partition with the ESP type AND that it is mounted. Both assumptions can fail when:
* you have multiple disks, each can have its own ESP (and UEFI can boot from any from its boot menu)
* by default systemd sets an automount for the ESP, so it's not even mounted by default - the `lsblk -o "PARTTYPE,MOUNTPOINT"` will print the UUID without any mount points.

This affects for ex. the `verify` command and probably others too.

the approach in systemd (bootctl) is to try[1] `"/efi"`, `"/boot"` and `"/boot/efi"`, and can be overridden with a `SYSTEMD_ESP_PATH` env var. And then it tries to also access[2] that path before deciding it's really an ESP.

[1] https://github.com/systemd/systemd/blob/c335b7c3f8164677316936c7a22e6fca85be28af/src/shared/bootspec.c#L1154
[2] https://github.com/systemd/systemd/blob/c335b7c3f8164677316936c7a22e6fca85be28af/src/shared/bootspec.c#L1080

sbctl could re-implement this same approach or somehow re-use the output of bootctl.

**Comment by ericonr** [comment]
I'd prefer not to depend on `bootctl`, since I don't have that here :P 

@Foxboron do you have any preference between a command line parameter or env vars? Looping through those directories seems reasonable to me, though. We could even implement logic to try and mount the ESP (if given in the command line or via env var) by calling `mount $ESP_PATH`, but I don't think that's entirely necessary.

**Comment by Foxboron** [comment]
You don't have `bootctl`?! terrible :)

I think we can implement the same logic and also look for `SYSTEMD_ESP_PATH` and `ESP_PATH` as fallbacks. Better to use the possible options we have available. Preferably not mess with mounting anything.

**Comment by Foxboron** [comment]
This is one of the more "this seems easy". But the missing part is that systemd checks with blkid and/or udev depending on privileged or unprivileged operation. I have no clue if the partition types is stores in procfs or sysfs or if there needs to be some simple partition introspection for this.

I might be over complicating this as well and we could just assume `BOOT/BOOTX64.EFI` should exist on one of those paths. Which should cover most of the usecases.

**Comment by igo95862** [comment]
From the systemd source code why it has both udev and blkid selection mechanism.

> /* If we are unprivileged we ask udev for the metadata about the partition. If we are privileged we
         * use blkid instead. Why? Because this code is called from 'bootctl' which is pretty much an
         * emergency recovery tool that should also work when udev isn't up (i.e. from the emergency shell),
         * however blkid can't work if we have no privileges to access block devices directly, which is why
         * we use udev in that case. */

**Comment by Foxboron** [comment]
Should we assume that `udev` is always available? And default to some silly checking for `BOOTx64.EFI` if that is not the case?

**Comment by igo95862** [comment]
I think `udev` is only available on systems with systemd or eudev. BTW, not sure why they are saying the `blkid` does not work in unpriviledged mode as it seems to work for me.

BTW there is a `wipefs` command that support JSON output.

**Comment by gdamjan** [comment]
> BTW, not sure why they are saying the `blkid` does not work in unpriviledged mode as it seems to work for me.

`blkid` doesn't work for unprivileged users (just check it). maybe you're part of the `disk` group.

**Comment by Foxboron** [comment]
I'm inclined to assume udev is available and leave the current approach by iterating over  `/efi`, `/boot``and `/boot/efi` as a fallback. Does that sound good? We can set a default ESP partition in the config when that is implemented.

**Comment by igo95862** [comment]
> > BTW, not sure why they are saying the `blkid` does not work in unpriviledged mode as it seems to work for me.
> 
> `blkid` doesn't work for unprivileged users (just check it). maybe you're part of the `disk` group.

I figured it out. When `blkid` is run it will create a cache file under `/run/blkid/blkid.tab`. After that unprivileged users can read the cache instead of the devices directly. There is some program that calls `blkid` on my system that creates that cache.

**Comment by igo95862** [comment]
> I'm inclined to assume udev is available and leave the current approach by iterating over `/efi`, `/boot` and `/boot/efi` as a fallback. Does that sound good? We can set a default ESP partition in the config when that is implemented.

Even if udev is available if there are multiple vfat partitions with ESP partition GUID (for example a user has inserted Arch boot ISO) how would you select.

**Comment by igo95862** [comment]
> I think we can follow the same logic?

Sounds good.

**Comment by Foxboron** [comment]
@igo95862 Want to try implement it :)?

**Comment by igo95862** [comment]
> @igo95862 Want to try implement it :)?

Closer to weekend probably.

BTW how would you want to add udev? Use some existing udev go binds? Link to libsystemd with cgo?

**Comment by Foxboron** [comment]
Preferably some existing udev go library would be the best option I think.

**Comment by igo95862** [comment]
How about this one: https://github.com/pilebones/go-udev

**Comment by Foxboron** [comment]
Hmm, there really wasn't that many udev libraries. That library is probably nice :)

**Comment by igo95862** [comment]
> Hmm, there really wasn't that many udev libraries. That library is probably nice :)

Well, its actually GPL3. Unless you want to re-license entire project...

**Comment by igo95862** [comment]
I think implementing the `blkid` is easier because it won't require any extra libraries just some command line parsing.

**Comment by Foxboron** [comment]
Hmm, lets go blkid and the ENV variables then we can figure out dbus later. It probably improves the status quo regardless :) Thanks!

**Comment by igo95862** [comment]
Actually that was the problem with `lsblk`. It can be used to retrieve the same information as `blkid` or udev plus output in JSON making parsing easy.

**Comment by Foxboron** [comment]
Ohhh! Neat! I'm not sure if this is new or I was completely blind to it when I implemented it the first time :)

**Comment by igo95862** [comment]
At least from March 2018 https://github.com/balena-io-modules/drivelist/pull/255
