### ISSUE TITLE
sbctl verify warns about unsigned binaries on permission error

### ISSUE THREAD

**Issue by lunaryorn** [Foxboron/sbctl#46]
sbctl complains that binaries aren't signed when in fact it just doesn't have access rights, i.e.

```
$ sbctl verify
==> Verifying file database and EFI images in /efi...
  -> WARNING: /efi/EFI/BOOT/BOOTX64.EFI is not signed
  -> WARNING: /efi/EFI/systemd/systemd-bootx64.efi is not signed
  -> /usr/lib/fwupd/efi/fwupdx64.efi.signed is signed
2021/04/03 09:57:38 open /efi: permission denied
```

In fact binaries are signed properly:

```
$  sudo sbctl verify
==> Verifying file database and EFI images in /efi...
  -> /efi/EFI/BOOT/BOOTX64.EFI is signed
  -> /efi/EFI/systemd/systemd-bootx64.efi is signed
  -> /usr/lib/fwupd/efi/fwupdx64.efi.signed is signed
  -> /efi/EFI/Linux/linux-5.10.27-1-lts-816184afa8524f2ca42a23ee0624abfb-rolling.efi is signed
  -> /efi/EFI/Linux/linux-5.11.11-arch1-1-816184afa8524f2ca42a23ee0624abfb-rolling.efi is signed
  -> WARNING: /efi/KeyTool.efi is not signed
```

I found the first message a bit scary; initially I thought I had done something wrong, when in fact I just had to call `sbctl verify` as root.

Perhaps the permission error could be made to stand out more?

**Comment by Foxboron** [comment]
Right, we should *probably* check for permissions before getting that far.

**Comment by lunaryorn** [comment]
Personally I think even just making the permission error in the last line stand out more, i.e. bold red font, would already help :slightly_smiling_face:
