### ISSUE TITLE
UEFI verification sometimes fail

### ISSUE THREAD

**Issue by demostanis** [Foxboron/sbctl#51]
After a kernel/systemd-boot upgrade and a reboot, UEFI might say verification failed.
I always have to grab my rescue livecd and reinstall kernel.
No errors.
Contents of `/usr/share/libalpm/hooks/99-sbctl.hook`: 
```ini
[Trigger]
Type = Path
Operation = Install
Operation = Upgrade
Operation = Remove
Target = boot/*
Target = efi/*
Target = usr/lib/modules/*/vmlinuz

[Action]
Description = Signing EFI binaries...
When = PostTransaction
Exec = /usr/bin/sbctl sign-all -g
```
`sbctl-git r74.gdfa6fb1-1`
`Linux archlinux 5.11.11-hardened1-1-hardened #1 SMP PREEMPT Sat, 03 Apr 2021 20:20:28 +0000 x86_64 GNU/Linux`

**Comment by Foxboron** [comment]
Right, I need to see a transaction or a copy of `/var/log/pacman.log` when it occurs :)

**Comment by demostanis** [comment]
```
[2021-03-20T18:03:30+0100] [ALPM] running '99-sbctl.hook'...
[2021-03-20T18:03:30+0100] [ALPM-SCRIPTLET] ==> Generating EFI bundles....
[2021-03-20T18:03:30+0100] [ALPM-SCRIPTLET] ==> /boot/EFI/BOOT/BOOTX64.EFI has been signed...
[2021-03-20T18:03:30+0100] [ALPM-SCRIPTLET] ==> /boot/EFI/systemd/systemd-bootx64.efi has been signed...
[2021-03-20T18:03:30+0100] [ALPM-SCRIPTLET]   -> Signing /boot/vmlinuz-linux-hardened...
```
```
[2021-03-06T07:59:40+0100] [ALPM] running '99-sbctl.hook'...
[2021-03-06T07:59:40+0100] [ALPM-SCRIPTLET] ==> Generating EFI bundles....
[2021-03-06T07:59:40+0100] [ALPM-SCRIPTLET]   -> Signing /boot/vmlinuz-linux-hardened...
[2021-03-06T07:59:40+0100] [ALPM-SCRIPTLET] ==> /boot/EFI/BOOT/BOOTX64.EFI has been signed...
[2021-03-06T07:59:40+0100] [ALPM-SCRIPTLET] ==> /boot/EFI/systemd/systemd-bootx64.efi has been signed...
```

**Comment by codicodi** [comment]
@demostanis I think some more context is needed regarding affected updates.

Specifically, do you use any custom means of updating your bootloader? Like [this hook](https://aur.archlinux.org/packages/systemd-boot-pacman-hook/l) perhaps?

**Comment by demostanis** [comment]
Yes,
`cat /etc/pacman.d/hooks/systemd-boot.hook`
```ini
[Trigger]
Type = Package
Operation = Upgrade
Target = systemd

[Action]
Description = Updating bootloader
When = PostTransaction
Exec = /usr/bin/bootctl update

```

**Comment by codicodi** [comment]
This hook needs to run before sbctl one does. Rename your custom hook to somthing like `95-systemd-boot.hook `

**Comment by demostanis** [comment]
Lemme try...

**Comment by demostanis** [comment]
Thanks, it didn't fail this time.
Should this be mentioned somewhere?

**Comment by Foxboron** [comment]
Nice catch @codicodi. I wonder if trying harder with the sbctl hook to be last would help as well?

@demostanis Did you get the filename from anywhere?

**Comment by demostanis** [comment]
@Foxboron I had written my hook by hand, and forgot to put `99-` at the start of the filename.

**Comment by codicodi** [comment]
One more potential issue is when systemd is updated, but not the kernel, sbctl won't run at all and bootloader will remain unsigned. Adding an extra trigger for systemd update in sbctl hook would solve that I guess... Sadly, the hook triggering logic has no way of knowing which bootloader is in use, so everyone has to accomodate for it manually

**Comment by codicodi** [comment]
@Foxboron the hook in AUR doesn't seem to use an ordering number either.

**Comment by Foxboron** [comment]
Right, but if I rename it to `zz-sbctl.hook` it should go last?

**Comment by codicodi** [comment]
Even better: `ZZ-sbctl.hook`. Seems slightly hacky to me though :)

**Comment by Foxboron** [comment]
Well, hacky or have people install their own hook.

The hook in general doesn't sign if you do `pacman -S mkinitcpio`. So I need to commit some changes and cut a release soon :)

**Comment by demostanis** [comment]
Doesn't dracut use other paths?

**Comment by Foxboron** [comment]
It does. Dracut doesn't have any hooks in the repositories for reasons I don't know. I could add the stuff from the AUR but not a priority on my end.

Should probably add booster as well.

https://github.com/anatol/booster/blob/master/packaging/arch/90-booster-install.hook#L6

**Comment by barmadrid** [comment]
Same issue. The hook is not triggering.
I use dracut and generate .efi file and boot directly with efistub (not bootloaders).

For example, once I run: `dracut --force --uefi /boot/linux.efi` the new file is not signed automatically, and nothing shows in `pacman.log`

Is this the expected behavior for my case?

**Comment by Foxboron** [comment]
Which hooks are you running for dracut? There is no official hooks so I'm not sure what targets we should be using.

**Comment by barmadrid** [comment]
I don't use any hooks. I just manually generate the file after I update the kernel.
