### ISSUE TITLE
ioutil should be removed in favour of io and/or os.

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/sbctl#55]
<pre>
λ sbctl master» egrep -nrH "io/ioutil" .          
./database.go:5:	"io/ioutil"
./keys.go:11:	"io/ioutil"
./util.go:8:	"io/ioutil"
./sbctl.go:7:	"io/ioutil"
./bundles.go:6:	"io/ioutil"
</pre>

Should be fairly easy I believe so a good first issue :)

https://golang.org/doc/go1.16#ioutil

**Comment by ericonr** [comment]
This will break compatibility with Go <1.16, right? Might matter for Debian (or other stable distro) users .

**Comment by Foxboron** [comment]
Debian is packaging 1.16 before they are packaging `sbctl` :) That is a bet I'm willing to take. `1.16` is also in Unstable so not that far off.
