### ISSUE TITLE
New CLI output format

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/sbctl#56]
Some mockups for sbctl interface that fits better with existing *ctl tooling.

Inspiration:
    * boltctl
    * fwupdmgr
    * bootctl

<pre>
✔ (Green)       Positive/Succsess
✘ (Red)         Negative/Error
‼ (Yellow)      Warning
⁇ (Yellow(?))   Unknwon/Exception/Somethingweird
</pre>

# Errors/Exceptions
<pre>
λ bin » sbctl list-bundles
⁇ It might be necessary to run this tool as root:
⁇ open /usr/share/secureboot/bundles.db: permission denied
(Bold red?)
</pre>

# Status
<pre>
$ sbctl status
✔ Secure Boot: Disabled
✔ Setup Mode:  User

Curent boot entry
✔ Signed / ✘ Not Signed (!)
    Title:		Arch Linux (systemd-linux.efi)
    Id:			systemd-linux.efi
    Source:		/efi/EFI/Linux/systemd-linux.efi
    Linux:		EFI/Linux/systemd-linux.efi
    Options:	rw quiet acpi_osi= acpi_backlight=thinkpad_screen nowatchdog bgrt_disable lockdown=confidentiality

json = {
    "Secure Boot": true,
    "Setup Mode": "user"
}
</pre>

# Verify
<pre>
$ sbctl verify
Verifying file database and EFI images in /efi...
✔ signed /boot/vmlinuz-linux
✔ signed /efi/EFI/BOOT/BOOTX64.EFI 
✔ signed /efi/EFI/Linux/linux-linux.efi
✔ signed /efi/EFI/Linux/systemd-linux.efi 
✔ signed /efi/EFI/arch/fwupdx64.efi 
✔ signed /efi/EFI/systemd/systemd-bootx64.efi 
✔ signed /usr/lib/fwupd/efi/fwupdx64.efi.signed 
✘ could not sign /efi/EFI/Linux/linux-linux-mitigations.efi

[
    {
        "file": "/boot/vmlinuz-linux"
        "is_signed": True,
    }
]
</pre>

# List Files
<pre>
$ sbctl list-files
Enrolled files:

/efi/EFI/arch/fwupdx64.efi
    Signed:		✔ Signed / ✘ Not Signed (!)

/efi/EFI/systemd/systemd-bootx64.efi
    Signed:		✔ Signed / ✘ Not Signed (!)

/usr/lib/fwupd/efi/fwupdx64.efi
    Output:		/usr/lib/fwupd/efi/fwupdx64.efi.signed
    Signed:		✔ Signed / ✘ Not Signed (!)

/boot/vmlinuz-linux
    Signed:		✔ Signed / ✘ Not Signed (!)

/efi/EFI/BOOT/BOOTX64.EFI
    Signed:		✔ Signed / ✘ Not Signed (!)

/efi/EFI/Linux/linux-linux.efi
    Signed:		✔ Signed / ✘ Not Signed (!)

/efi/EFI/Linux/systemd-linux.efi
    Signed:		✔ Signed / ✘ Not Signed (!)
</pre>

# List Bundles
<pre>
$ sudo sbctl list-bundles
Enrolled bundles:

/efi/EFI/Linux/linux-linux.efi
    ESP Location:       /efi
    Output:             └─/EFI/Linux/linux-linux.efi
    EFI Stub Image:       └─/usr/lib/systemd/boot/efi/linuxx64.efi.stub
    Splash Image:           ├─/usr/share/systemd/bootctl/splash-arch.bmp
    Cmdline:                ├─/etc/kernel/cmdline
    OS Release:             ├─/usr/lib/os-release
    Kernel Image:           ├─/boot/vmlinuz-linux
    Initramfs Image:        └─/boot/initramfs-linux.img
    Intel Microcode:          └─/boot/intel-ucode.img
    Signed:             ✔ Signed / ✘ Not Signed (!)
</pre>

**Comment by ericonr** [comment]
Supporting json output would be nice for parsing purposes, since the new pretty format looks slightly harder to parse.

**Comment by Foxboron** [comment]
I'd like to have "-j/--json" supported as a top-level flag. I *think* it should be fairly easy to support this pr command.

**Comment by Foxboron** [comment]
Some more mockup

![image](https://user-images.githubusercontent.com/1042946/115149191-46810880-a063-11eb-8d7d-b4078f1d5e26.png)
