### ISSUE TITLE
Replace `log.Fatal` with `log.Panic`?

### ISSUE THREAD

**Issue by igo95862** [Foxboron/sbctl#59]
`log.Fatal`:
```
2021/05/04 15:10:55 exit status 1
exit status 1
```
VS

`log.Panic`:
```
2021/05/04 15:09:17 exit status 1
panic: exit status 1

goroutine 1 [running]:
log.Panic(0xc0000b3dc8, 0x1, 0x1)
	/usr/lib/go/src/log/log.go:354 +0xae
github.com/foxboron/sbctl.GetESP(0x656580, 0xc000066840)
	/home/user/Projects/sbctl/sbctl.go:26 +0x176
main.bundleCmd(0x7e1d00)
	/home/user/Projects/sbctl/cmd/sbctl/main.go:235 +0x249
main.main()
	/home/user/Projects/sbctl/cmd/sbctl/main.go:338 +0x1fc
exit status 2
```

I think having trackbacks is very nice for debugging and bug reports.

**Comment by ericonr** [comment]
I think error messages should be improved so `log.Fatal` isn't used at all. Neither of those messages is user friendly, since a lot of the `log.Fatal` calls should tell the user what went wrong so they have an idea of how to fix, not need to open a bug report to understand what went wrong.

**Comment by Foxboron** [comment]
I think the current error handling in sbctl is quite bad. A lot of it has been added as an after though, but I reckon a redesign with propper error wrapping would do wonders. I don't think replacing Fatal with Panic is useful in of itself, but there needs to be work on how to approach error handling. I have been experimenting with a better layout locally with another tool in relation to #56
