### ISSUE TITLE
Implement sbctl.conf

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/sbctl#6]
There are a few lines which should probably be refactored into `config.go`. Mainly the files in [keys.go](https://github.com/Foxboron/sbctl/blob/master/keys.go#L22-L33).

I think we should leave room to specify which protocol one want, files vs yubikey and so on. Along with desired RSA key sizes.

Can probably use yaml or toml for the file itself. Not super keen on having json.

**Comment by Foxboron** [comment]
Currently I have toyed with the idea of utilizing toml for this. I have also mocked up an example config.


```
[keys]
keysize = 4096

[keys.PK]
backend = "hw"

[keys.KEK]
backend = "files"

[keys.db]
backend = "files"

[backend.files]
type = "directory"
path = "/usr/share/secureboot"

[backend.hw]
type = "yubikey"
cardid = "fasdfasd"
```

**Comment by beroal** [comment]
Hi. Is this configuration file already used? If yes, where it resides in the file system?

`/usr/share/secureboot` is readable by all users of the computer and isn't encrypted. I believe that keys should be secret. I want to change this path to a more secure place.

**Comment by Foxboron** [comment]
@beroal It's not been implemented yet. Using current secure boot tooling without full disk encryption is a bit useless until HSM or TPM support is implemented.

**Comment by beroal** [comment]
Even with full disk encryption, `/usr/share/secureboot` is readable by all users.

**Comment by ericonr** [comment]
@beroal the keys can be chmod'd to be readable only by root (as sbctl does).

**Comment by Scrumplex** [comment]
> @beroal the keys can be chmod'd to be readable only by root (as sbctl does).

This change (ea325ca46fec8b75ac6dd89742d2ea714593d38f) is not in the latest tag! So only people running from Git master have this. 

But one can be easily fix this like this:
```bash
# find /usr/share/secureboot/keys -type f -exec "chmod" "400" "{}" \;
```

**Comment by Foxboron** [comment]
Please see https://github.com/Foxboron/sbctl/issues/57#issuecomment-2233744465

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/commit/4f31817e14063335e04984a167edf72777d089e0
