### ISSUE TITLE
Is spliting arguments by white space some legacy code or does it serve a purpose?

### ISSUE THREAD

**Issue by igo95862** [Foxboron/sbctl#60]
```
args := fmt.Sprintf("--cert %s %s", cert, file)
cmd := exec.Command("sbverify", strings.Split(args, " ")...)
```
Is same as:
```
cmd := exec.Command("sbverify", "--cert", cert, file)
```
But with support for white space in directories and file names.

**Comment by ericonr** [comment]
Probably not legacy code, given that `sbctl` is comfortable requiring Go 1.16. I think it should be fine to PR as a fix, though I hope people aren't using directories with white space for this stuff :p

**Comment by Foxboron** [comment]
:D

I don't recall why I wrote it like that :) Probably fine to send a PR for it!

**Comment by igo95862** [comment]
> I don't recall why I wrote it like that :) Probably fine to send a PR for it!

Will do

**Comment by igo95862** [comment]
https://github.com/Foxboron/sbctl/blob/9060461b35c5acf33d71a968de5e1710eae23b53/keys.go#L113

https://github.com/Foxboron/sbctl/blob/9060461b35c5acf33d71a968de5e1710eae23b53/keys.go#L148

Why are certain commands called by full path but some by name only (aka by PATH lookup)?

**Comment by Foxboron** [comment]
I don't remember :) I think `$PATH` lookup makes more sense maybe?
