### ISSUE TITLE
Shell completions are corrupted.

### ISSUE THREAD

**Issue by igo95862** [Foxboron/sbctl#62]
![Screenshot from 2021-05-05 10-09-33](https://user-images.githubusercontent.com/8576552/117107306-e67fa700-ad70-11eb-8f36-623df7d1f61a.png)

All of shell completions have this binary string at the end.

In `less` it looks like this:

`ESC(BESC[m`

Probably an issue with upstream library?

**Comment by Foxboron** [comment]
This is an inherent issue with how I have implemented the terminal colors. All commands are closed off with that escape code for no good reason.

https://github.com/Foxboron/sbctl/blob/master/cmd/sbctl/main.go#L352

I should try and implement the new command structure with the cli output to fix this :/ Is it completely broken with fish? zsh works fine with the escape at the bottom.

**Comment by igo95862** [comment]
> Is it completely broken with fish?

Yes. Fish is strict about script formatting.

**Comment by igo95862** [comment]
BTW. Why not write to some file directly instead of stdout? Probably avoids the issue but require slight PKGBUILD modification.

**Comment by Foxboron** [comment]
I think generally restructuring the AddCommand section to add `PostRun` with the off switch on everything except the completion stuff is the way to go.

**Comment by igo95862** [comment]
I think it is also possible to send control sequences in to `stderr` instead of `stdout`. Usually but will be linked to same pipe as `stdout` but in case of shell redirect `>` only `stdout` will be redirected.

**Comment by igo95862** [comment]
Ok. I tested changing `fmt.Print(off)` to `fmt.Fprint(os.Stderr, off)` and it works.  Shell scripts are no longer corrupted and colors are still displayed. This is a one line change.
