### ISSUE TITLE
Move JSON databases to use `.json` extension? Helps the text editors to use JSON highlights and formatting. 

### ISSUE THREAD

**Issue by igo95862** [Foxboron/sbctl#63]
Right now they have `.db` extension but they are just JSON files.

Can be done in backward compatible way. (check for `.db` but default to `.json`)

**Comment by WhyNotHugo** [comment]
Might make sense to make this change along with  #57, so that there's only one release with this sort of breaking changes.

**Comment by igo95862** [comment]
> one release with this sort of breaking changes

It does not have to be breaking. A simple check of old location if new one fails is sufficient to provide backward compatibility.

**Comment by Foxboron** [comment]
It doesn't, but it makes the entire change set easier if we pool up all these changes to one larger "move from misuing /usr to proper /var and /etc".

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/commit/4f31817e14063335e04984a167edf72777d089e0
