### ISSUE TITLE
Provide a more sophisticated way to select up to n initrd image files for generating bundles

### ISSUE THREAD

**Issue by mrblumi** [Foxboron/sbctl#65]
Some stuff - such as [Full disk encryption with Yubikey](https://github.com/eworm-de/mkinitcpio-ykfde/blob/master/README-mkinitcpio.md) requires setting a third initrd file between $-ucode.img and initramfs-$.img 

Maybe something like an advanced flag -m first.img second.img third.img... to provide all $.img files in personal order would be possible?

**Comment by Foxboron** [comment]
The entire `mkinitcpio-ykfde` is deprecated with the introduction of the latest systemd release as it supports `cryptenroll` with FIDO keys, PKCS11 and TPMs. This is *extremely* easy to setup if you first use a systemd enabled initramfs.

http://0pointer.net/blog/unlocking-luks2-volumes-with-tpm2-fido2-pkcs11-security-hardware-on-systemd-248.html


So I'm not going to introduce more features to the `sbctl` bundle code for this :)

`booster` and `mkinitcpio` is also going to get support for generating UEFI executables so I'm contemplating a bit if this feature as a whole is needed in sbctl going forward.

https://github.com/golang/go/pull/45681

https://github.com/anatol/booster/commit/c31dccf4d4e349194484c1fd1b9665eca30b79fe

**Comment by mrblumi** [comment]
Oh, I must have missed this - sorry :)

**Comment by Foxboron** [comment]
No worries :) Not easy to pay attention to everything being added to software
