### ISSUE TITLE
Move from execing sbsigntools to goefi

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/sbctl#7]
The end goal is to utilize goefi for all secure boot operations. Currently it should have all the supported interfaces we need, but need to experiment on some top-level APIs.

https://github.com/Foxboron/goefi

**Comment by rgl** [comment]
Can you please link the commit/PR that added this? :-)

Was it https://github.com/Foxboron/sbctl/commit/7192e52fa1c02d648f9567184da5f8efd5a9f513?

**Comment by Foxboron** [comment]
Here is the merge commit, https://github.com/Foxboron/sbctl/commit/32ac2678342aab8233ee887ea73cc781e907f86a

The change was done over several commits so there isn't any one particular commit for it.
