### ISSUE TITLE
Sweet! ZBM Support?

### ISSUE THREAD

**Issue by dm17** [Foxboron/sbctl#73]
I wonder if we can expect this to play nicely with zfsbootmenu? https://github.com/zbm-dev/zfsbootmenu
Would be great if you worked together with rEFInd & ZBM to get a verified boot working with these awesome tools.
Would love to get your thoughts on this thread: https://github.com/zbm-dev/zfsbootmenu/issues/36#issuecomment-799545482

**Comment by Foxboron** [comment]
@ericonr has contributed to sbctl and zfsbootmenu, so I think they could help answer. My immediate reaction is that it should be possible to just point at the keys with dracut and sign normally. Some things might be easier when I start working on the config file code.

**Comment by ericonr** [comment]
Doing it with dracut is indeed a breeze, though I'm currently using only `sbctl` now that the `sbsigntools` dependency has been removed.

See `uefi_secureboot_cert` and `uefi_secureboot_key` in https://man.voidlinux.org/dracut.conf.5 . You just need to add them to the dracut config dir used by `zbm_generate`: `/etc/zfsbootmenu/dracut.conf.d`

**Comment by Foxboron** [comment]
I don't see what sbctl should be doing. Closing the issue :)
