### ISSUE TITLE
private keys shouldn't be world-readable

### ISSUE THREAD

**Issue by EvilBit** [Foxboron/sbctl#82]
All key material, including private keys, are created world-readable ([`0644` here](https://github.com/Foxboron/sbctl/blob/78cdabfa6da24e0fb1da84e03d9f74a1d805faf9/keys.go#L90)) at the moment.

Exposing this secret key material to unprivileged users and processes poses a security vulnerability.

**Comment by EvilBit** [comment]
Oh, and by the way, thanks **a lot** for this great tool - finally a workable secure boot management tool :)

**Comment by Foxboron** [comment]
Yolo, copy-pasted code. Thanks :)

**Comment by ericonr** [comment]
Interesting, my keys are 600... I wonder when the regression happened.

**Comment by EvilBit** [comment]
> Interesting, my keys are 600... I wonder when the regression happened.

I just traversed backwards through `git blame` and the permissions in `SaveKey` were `0644` since the [initial commit](https://github.com/Foxboron/sbctl/blob/0b5d4a46eaf0cd6e2bb36a0a5b2ba46802388b52/keys.go#L71).

But [here](https://github.com/Foxboron/sbctl/commit/1bf2810228431862f301e52ca4121cd0b7805346#diff-a0896c3a091e9111074431503f5eb3a62aa117962efd8f4033f905a2c2df356cL71) the initial creation of the files was removed from `CreateKey` (which set `0600`) and relied now on the erroneous permissions in `SaveKey`.

**Comment by EvilBit** [comment]
Maybe the code should even check for too permissive file permissions and refuse signing in this case. Like OpenSSH [enforces it for private keys](https://github.com/openssh/openssh-portable/blob/2dc328023f60212cd29504fc05d849133ae47355/authfile.c#L106).

**Comment by ericonr** [comment]
I think that's reasonable, but please with better error messages :p

**Comment by Foxboron** [comment]
We can just do an `var ErrInvalidPrivKeyPersm = erros.new("...something")` and match it in `main.go` to give something human readable error back.

https://github.com/Foxboron/sbctl/blob/master/cmd/sbctl/main.go#L69-L78

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/sbctl/commit/ea325ca46fec8b75ac6dd89742d2ea714593d38f
