### ISSUE TITLE
the `pem` file extension

### ISSUE THREAD

**Issue by beroal** [Foxboron/sbctl#87]
Is there a reason to choose the `pem` file extension? Other Secure Boot tools ([gdamjan/secure-boot](https://github.com/gdamjan/secure-boot), [andreyv/sbupdate](https://github.com/andreyv/sbupdate)) expect the extension to be `crt`.

**Comment by Foxboron** [comment]
They are generally used interchangeably. Is this a problem or a general gripe?

**Comment by beroal** [comment]
> Is this a problem or a general gripe?

There is a problem with `sbupdate`: it can't use files produced by sbctl when `KEY_DIR="/usr/share/secureboot/keys/db"` is set in `sbupdate`'s configuration file. The error message is
```
Generating and signing linux-signed.efi
warning: data remaining[18301440 vs 18311414]: gaps between PE/COFF sections?
warning: data remaining[18301440 vs 18311416]: gaps between PE/COFF sections?
Can't load certificate from file '/usr/share/secureboot/keys/db/@(DB|db).crt'
140023984573440:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/usr/share/secureboot/keys/db/@(DB|db).crt','r')
140023984573440:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
```
`sbupdate` works if I rename `db.pem` to `db.crt`.

**Comment by Foxboron** [comment]
`sbupdate` and `sbctl` serves the same purpose. It's unclear to me why you want to use them both?

**Comment by beroal** [comment]
AFAIK, `sbctl` doesn't update a unified kernel image if any of the source files is changed.

**Comment by Foxboron** [comment]
That should be dealt with a hook when you update your system. Is it not working for you?

**Comment by beroal** [comment]
Well, `sbupdate` contains this hook.

**Comment by Foxboron** [comment]
Yes, and `sbctl` has a similar hook that runs. I'm not sure what the actual problem is.

**Comment by beroal** [comment]
Okay, I didn't see your hook. Thanks!

**Comment by Foxboron** [comment]
No problem :)
