### ISSUE TITLE
`list-bundles` gives an error if a bundle is absent in the file system

### ISSUE THREAD

**Issue by beroal** [Foxboron/sbctl#88]
I understand that the `bundle` command creates a _bundle description_ in `/usr/share/secureboot/bundles.db` and creates the bundle (file). I suppose that `${NAME}` in `sbctl bundle ${NAME}` is the path to the bundle; this is not clear from the man page.

Executing
```
sbctl bundle --amducode /boot/amd* --save /boot/efi/boot/bootx64.efi
rm /boot/efi/boot/bootx64.efi
sbctl list-bundles
```
gives
```
Wrote EFI bundle /boot/efi/boot/bootx64.efi
open /boot/efi/boot/bootx64.efi: no such file or directory
```

The program doesn't show the bundle description for `/boot/efi/boot/bootx64.efi` despite that it exists in `/usr/share/secureboot/bundles.db`. Not showing it as a normal entry is confusing. Also `sbctl list-bundles` shows no bundle descriptions at all (if there are more than one) if at least one bundle is absent in the file system. For a mysterious reason, I see bundle descriptions for bundles that are present in the file system when I redirect the program output to a file.

I believe that user deleting a bundle is a realistic scenario.

P. S. I guess that the default paths that start with `/efi` should be fixed on the man page. It seems that in my case, `/boot` is the default:
```
Enrolled bundles:

/boot/efi/boot/bootx64.efi
	Signed:		✔ Signed
	ESP Location:	/boot
	Output:		└─/efi/boot/bootx64.efi
	EFI Stub Image:	  └─/usr/lib/systemd/boot/efi/linuxx64.efi.stub
	Cmdline:	    ├─/etc/kernel/cmdline
	OS Release:	    ├─/usr/lib/os-release
	Kernel Image:	    ├─/boot/vmlinuz-linux
	Initramfs Image:    └─/boot/initramfs-linux.img
	AMD Microcode:        └─/boot/amd-ucode.img
```

**Comment by ml-** [comment]
Similar behavior with `list-files` if one of the files is missing.

```shell
# While there are multiple files in /usr/share/secureboot/files.db, the command fail as soon as one file can not be found.
# Expected behavior would be to output all the files alongside the errors
$ sbctl list-files 
open /boot/EFI/BOOT/BOOTX64.EFI: no such file or directory

# Adding --json flag results in no output. This is not the same as having no files added, as it would output a empty json array '[]'
$ sbctl --json list-files
(no output)

# However removing works fine
$ sbctl remove-file /boot/EFI/BOOT/BOOTX64.EFI
Removed /boot/EFI/BOOT/BOOTX64.EFI from the database.
```

**Comment by Foxboron** [comment]
>P. S. I guess that the default paths that start with /efi should be fixed on the man page. It seems that in my case, /boot is the default:

I'm not sure where you are looking? Please submit a bugreport if it's an issue :)
