### ISSUE TITLE
Error: Verification Requested but nobody cares: GRUB Rescue

### ISSUE THREAD

**Issue by garvit-joshi** [Foxboron/sbctl#91]
Hey,
I ran up with an issue with GRUB: Error
```
error: Verification Requested but nobody cares: (hd0,gpt2)/boot/grub/x86_64-efi/normal.mod
Entring Resue Mode....
grub resue>
```
This is everything i have done
```
➜  ~ sudo sbctl verify
[sudo] password for garvit-joshi: 
Verifying file database and EFI images in /boot/efi...
✔ /boot/efi/EFI/Manjaro/grubx64.efi is signed
✔ /boot/efi/EFI/boot/bootx64.efi is signed

➜  ~ sudo sbctl status
Installed:      ✔ Sbctl is installed
Owner GUID:     8c9a1ec8-e588-40eb-a184-0576f1e3ffc9
Setup Mode:     ✔ Disabled
Secure Boot:    ✘ Disabled

➜  ~ sudo sbctl list-files
/boot/efi/EFI/Manjaro/grubx64.efi
Signed:         ✔ Signed

/boot/efi/EFI/boot/bootx64.efi
Signed:         ✔ Signed

```
the grub resue comes when I enable secure boot after doing everything as in Readme.md.

**Comment by garvit-joshi** [comment]
I am not that expert in EFI and Could not understand ```Generate EFI Stub``` in Readme.md. So I have not done those things.

**Comment by Foxboron** [comment]
This is an issue with grub and secure boot after the last series of patches for boothole. You need to build grub EFI executable with all the modules built in. This is a distribution issue, but one that lacks all the documentation upstream as well.

Something like described here can be done: https://github.com/Antynea/grub-btrfs/issues/156

**Comment by garvit-joshi** [comment]
This Helped.
After ```grub-install```  I signed ```/boot/efi/EFI/GRUB/grubx64.efi``` and secure boot works.
Thank You for the help.
