### ISSUE TITLE
generate-bundles throws odd error when files missing

### ISSUE THREAD

**Issue by ml-** [Foxboron/sbctl#92]
Moved ESP from `/boot` to `/efi` and thought I'd quickly reinstall **linux** and **intel-ucode** to recreate the files at `/boot`.
The `sbctl generate-bundles -s`, which is executed via pacman hook throw these errors:

```plaintext
Generating EFI bundles....
objcopy: /boot/EFI/Linux/linux.efi: Bad file descriptor
objcopy: --change-section-vma .splash=0x0000000000040000 never used
objcopy: --change-section-vma .initrd=0x0000000003000000 never used
objcopy: --change-section-vma .linux=0x0000000002000000 never used
objcopy: --change-section-vma .cmdline=0x0000000000030000 never used
objcopy: --change-section-vma .osrel=0x0000000000020000 never used
failed creating bundle /boot/EFI/Linux/linux.efi: failed to generate bundle /boot/EFI/Linux/linux.efi
/boot/EFI/BOOT/BOOTX64.EFI does not exist
```

While it 100% is my fault for not doing things in the right order, I still think the error message should be a different one.

**Comment by Foxboron** [comment]
Not going to working more on the UKI stuff, better to use the initramfs generator for this.
