### ISSUE TITLE
Grub Error

### ISSUE THREAD

**Issue by Xenfo** [Foxboron/sbctl#94]
I am getting this error:
```
error: Verification Requested but nobody cares: (hd0,gpt2)/boot/grub/x86_64-efi/normal.mod
Entring Resue Mode....
grub resue>
```

I followed #91 but no luck.

`sbctl verify`
```
✓ /boot/EFI/EFI/GRUB/grubx64.efi is signed
✓ /boot/EFI/EFI/arch/grubx64.efi is signed
✓ /boot/EFI/Linux/linux-linux.efi is signed
✓ /boot/EFI/grub/grubx64.efi is signed
✓ /boot/grub/x86_64-efi/core.efi is signed
✓ /boot/grub/x86_64-efi/grub.efi is signed
✓ /boot/vmlinuz-linux is signed
```
`sbctl list-bundles`
```
Enrolled bundles:

/boot/EFI/Linux/linux-linux.efi
        Signed:         ✓ Signed
        ESP Location:   /boot
        Output:         └─/EFI/Linux/linux-linux.efi
        EFI Stub Image:   └─/usr/lib/systemd/boot/efi/linuxx64.efi.stub
        Splash Image:       ├─/usr/share/systemd/bootctl/splash-arch.bmp
        Cmdline:            ├─/proc/cmdline
        OS Release:         ├─/usr/lib/os-release
        Kernel Image:       ├─/boot/vmlinuz-linux
        Initramfs Image:    └─/boot/initramfs-linux.img
        Intel Microcode:      └─/boot/intel-ucode.img
```

I also have no clue what a bundle means (can someone explain?), or why I have so many Grubs (do I need to get rid of some?).

**Comment by Foxboron** [comment]
This is a grub issue, not a sbctl issue. You need to build the grub EFI binary without the shim verifier and with all modules you are probably going to use. How did you install grub?

**Comment by Xenfo** [comment]
I used a script to install Arch here's how it installed grub
```sh
pacman_install "grub dosfstools"
arch-chroot /mnt sed -i 's/GRUB_DEFAULT=0/GRUB_DEFAULT=saved/' /etc/default/grub
arch-chroot /mnt sed -i 's/#GRUB_SAVEDEFAULT="true"/GRUB_SAVEDEFAULT="true"/' /etc/default/grub
arch-chroot /mnt sed -i -E 's/GRUB_CMDLINE_LINUX_DEFAULT="(.*) quiet"/GRUB_CMDLINE_LINUX_DEFAULT="\1"/' /etc/default/grub
arch-chroot /mnt sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="'"$CMDLINE_LINUX"'"/' /etc/default/grub
echo "" >>/mnt/etc/default/grub
echo "# alis" >>/mnt/etc/default/grub
echo "GRUB_DISABLE_SUBMENU=y" >>/mnt/etc/default/grub

pacman_install "efibootmgr"
arch-chroot /mnt grub-install --target=x86_64-efi --bootloader-id=grub --efi-directory=$ESP_DIRECTORY --recheck

arch-chroot /mnt grub-mkconfig -o "$BOOT_DIRECTORY/grub/grub.cfg"
```

**Comment by Foxboron** [comment]
Right, there are multiple issues here because you are using a script + installing grub twice. The last line is also targeting the wrong ESP partition and essentially installing a new bootloader. `efibootmgr -v` should give you `grub` and `GRUB`. Rest of it should be correct though.

This isn't a sbctl issue, so I'll close the issue. Sorry!

**Comment by Xenfo** [comment]
May I know what a bundle is though?

**Comment by Foxboron** [comment]
A "bundle" is an EFI binary that contains your kernel cmdline, initramfs and the kernel. Traditionally with secure boot you could only sign the kernel. But that leaves you with any boot configuration or initramfs susceptible of tampering as they won't be signed during boot.

**Comment by Xenfo** [comment]
Do I have to do anything with the bundles after I run generate bundles or is it automatically dealt with?

**Comment by Foxboron** [comment]
I don't know what you mean with "automatically dealt with". You need to sign them and then if you want to use them during boot you need to tell your bootloader about them.

**Comment by Xenfo** [comment]
Alright thank you for the help. Hopefully I can figure this out.

**Comment by Xenfo** [comment]
I'm struggling on how I would tell Grub to use my EFI Stub, unless an EFI Stub is only needed for using UEFI directly.

My bundle:
```
sudo sbctl bundle -s -i /boot/intel-ucode.img -c /proc/cmdline /boot/EFI/Arch/Arch-Linux.efi

sudo sbctl generate-bundles
```

Thanks!

**Comment by Foxboron** [comment]
Something like this I reckon, https://wiki.archlinux.org/title/GRUB#EFI_binaries

**Comment by Xenfo** [comment]
So I would have to manually add it to the config? If so wouldn't it just get deleted when I update Grub or run `grub-mkconfig`?

**Comment by Foxboron** [comment]
I don't know grub and abstractions people use for it, sorry.

**Comment by Xenfo** [comment]
Alright thanks for all the help!
