### ISSUE TITLE
Dual Booting Windows

### ISSUE THREAD

**Issue by Xenfo** [Foxboron/sbctl#95]
Is dual booting Windows on a separate drive currently possible?

**Comment by Foxboron** [comment]
It depends on the bootloader.

This issue tracker is for issues and features around `sbctl`. I do not have the bandwidth to help and answer questions or issues about system setup and other boot related issues.

**Comment by Xenfo** [comment]
What I meant is if there is a way to also use current UEFI keys instead of creating new ones because then I can't boot Windows.
