### ISSUE TITLE
verify does not show all EFI binaries

### ISSUE THREAD

**Issue by kleinph** [Foxboron/sbctl#96]
`sbclt verify` does not show all EFI binaries. Notable missing ones are:

- _/boot/EFI/systemd/systemd-bootx64.efi_
- _/boot/EFI/arch/fwupdx64.efi_

After signing these files, they show up on `sbctl verify` (as they are stored in the database now, I assume).

Note that the ESP is mounted to /boot.

Tested with sbctl version 0.6-1

**Comment by Foxboron** [comment]
What's the complete output of `sbctl verify`, and does `ESP_PATH=/boot sbctl verify` change the output?

**Comment by kleinph** [comment]
Thanks for the quick response!

(I deleted all files with `sbctl remove-file` before doing this.)

Complete output of `sbctl verify`:
````
sbctl verify 
Verifying file database and EFI images in /boot...
✔ /boot/EFI/Boot/BOOTX64.EFI is signed

✘ /boot/EFI/Boot/LenovoBT.EFI is not signed

✔ /boot/EFI/Linux/arch-linux.efi is signed

EOF
````
Prepending `ESP_PATH=/boot` doesn't change the output.

BTW there are more EFI executables which are not listed (leftovers from the pre-installed Windows):

````
fd --glob *.efi /boot/
/boot/EFI/Boot/BOOTX64.EFI
/boot/EFI/Boot/LenovoBT.EFI
/boot/EFI/Linux/arch-linux.efi
/boot/EFI/Microsoft/Boot/bootmgfw.efi
/boot/EFI/Microsoft/Boot/bootmgr.efi
/boot/EFI/Microsoft/Boot/memtest.efi
/boot/EFI/arch/fwupdx64.efi
/boot/EFI/systemd/systemd-bootx64.efi
````
