### ISSUE TITLE
Error when using sing with --output flag

### ISSUE THREAD

**Issue by kleinph** [Foxboron/sbctl#98]
Trying to sign the fwupd binary as described in the README gives following error:

````
# sbctl sign -s /usr/lib/fwupd/efi/fwupdx64.efi -o /usr/lib/fwupd/efi/fwupdx64.efi.signed
open /usr/lib/fwupd/efi/fwupdx64.efi.signed: no such file or directory
````

This also occurs when trying to sign other files with the `--output` flag.

**Comment by ericonr** [comment]
I couldn't reproduce this. Can you try with latest sbctl?

**Comment by kleinph** [comment]
I confirm that this issue does not occur anymore with version 0.7.

**Comment by Foxboron** [comment]
Lovely, thanks for for checking :)
