### ISSUE TITLE
Add warning to verify or enroll-keys command if Microsoft cert is not installed into UEFI

### ISSUE THREAD

**Issue by nathanielcwm** [Foxboron/sbctl#99]
TItle

Reading some of the existing issue threads here I was mistakenly given the impression that sbctl automatically installed the Microsoft cert alongside the generated self signed cert. Having a clear warning would alleviate this issue entirely.

Alternatively a warning could be added to the man page or/and readme instead.

**Comment by Foxboron** [comment]
Yo!

I have some code that attempts to parse the tpm eventlog and give a suggestion when you run `enroll-keys`. It would give you the option of enrolling the microsoft CA, try enroll all OPROM checksums into the `db` or just give you the option of `--yolo` which would be what it currently does. Hopefully it should be in some shape within the new week(s) or so.

**Comment by Foxboron** [comment]
`sbctl` now has support for Microsoft OEM keys in master. I'll implement a warning thing for `enroll-keys` before a release.

https://github.com/Foxboron/sbctl/issues/40#issuecomment-962476052

**Comment by Foxboron** [comment]
Implemented with https://github.com/Foxboron/sbctl/commit/8b1bade601df0747d3475426dea07ea46e920149
